### ISSUE TITLE
tracing-futures: What's blocking the 0.3 release?

### ISSUE THREAD

**Issue by d-e-s-o** [tokio-rs/tracing#1180]
Please see above. I see [`Cargo.toml`](https://github.com/tokio-rs/tracing/blob/master/tracing-futures/Cargo.toml) already mentioning version `0.3`, but can't seem to find it on `crates.io`. What's the hold up? Also, 971a46b46d5057daaa11bf8d9081f10ba69935d6 tagged version 0.2.6, which is also not available on `crates.io` ...?

**Comment by hawkw** [comment]
>  I see [`Cargo.toml`](https://github.com/tokio-rs/tracing/blob/master/tracing-futures/Cargo.toml) already mentioning version `0.3`, but can't seem to find it on `crates.io`. What's the hold up?

The current master branch is targeting `tracing` 0.2.x development --- `tracing-futures` on master has its version bumped to 0.3 because updating the `tracing` dependency to 0.2.x *will* be a breaking change, when 0.2 is released. The current state of the released versions is on the [ `v0.1.x` branch](https://github.com/tokio-rs/tracing/tree/v0.1.x).

You can track progress on `tracing` 0.2 in issues #922 and #923. The honest answer to the question "what's the hold-up?" is that work on 0.2 has been progressing fairly slowly because I have other responsibilities as well, and have been prioritizing maintenance for the released v0.1.x ecosystem over working on the breaking changes.

> Also, [971a46b](https://github.com/tokio-rs/tracing/commit/971a46b46d5057daaa11bf8d9081f10ba69935d6) tagged version 0.2.6, which is also not available on `crates.io` ...?

Hmm, that looks like a mistake --- as you can see from the commit message, that commit was supposed to update the _`tracing-subscriber` crate_'s version to 0.2.6. It looks like the `tracing-futures` version in Cargo.toml was only changed due to a find-and-replace mistake. My bad! As you can see, [the latest version in the changelog is 0.2.4](https://github.com/tokio-rs/tracing/blob/v0.1.x/tracing-futures/CHANGELOG.md#024-april-21-2020).

Hopefully that helps answer your questions --- is there any specific unreleased change you're waiting for?

**Comment by d-e-s-o** [comment]
Interesting. Thanks for the explanation. The background of my question is that `tracing-futures` 0.2 pulls in `pin-project ^0.4`, which is now causing a duplication with other crates (e.g., `hyper`) that moved on to depending on `1.0`. I'd like to get rid of this duplication where possible. The bump has happened already on the `master` branch of `tracing-futures` (cd911e069e4f7761b95a215d409792bcde32e15a).

Is there any chance another `0.2` release cut be cut that includes this bump as well? That is, if I were to submit a pull request bumping the dependency, would it be accepted (and a new `0.2` release be cut eventually)?

**Comment by benesch** [comment]
> Is there any chance another 0.2 release cut be cut that includes this bump as well? That is, if I were to submit a pull request bumping the dependency, would it be accepted (and a new 0.2 release be cut eventually)?

We at @MaterializeInc would also really appreciate a release with this bump!

**Comment by d-e-s-o** [comment]
Seems to have been fixed with `0.2.5`. Thanks!
