### ISSUE TITLE
tracing::subscriber::with_default breaks instrument/span used with future.

### ISSUE THREAD

**Issue by lambdalisue** [tokio-rs/tracing#1328]
### Version

- tracing v0.1.25 (*)
- tracing-subscriber v0.2.17 (*)

### Platform

macOS Catalina (10.15.7)

### Description

Using `tracing::subscriber::with_default` seems to drop instrument?
I've tried with the following code and the first `test().await` shows `INFO test: Hello` but the second one shows `INFO Hello` with some "panicked" log.

```rust
use tracing::{info, instrument, Instrument as _};
use tracing_subscriber::layer::SubscriberExt;

fn main() {
    let subscriber = || {
        let layer = tracing_subscriber::fmt::layer()
            .with_target(false)
            .with_thread_names(false);
        tracing_subscriber::registry().with(layer)
    };
    let _ = tracing::subscriber::set_global_default(subscriber());

    // Following shows 'INFO test: Hello'
    async_std::task::block_on(async move {
        test().await;
    });

    // Following shows 'INFO Hello' then shows the following panic log
    //
    //  thread 'async-std/runtime' panicked at 'tried to drop a ref to Id(1), but no such
    //  span exists!', /.../tracing-subscriber-0.2.17/src/registry/shared.rs:273:21
    //
    tracing::subscriber::with_default(subscriber(), move || {
        async_std::task::block_on(async move {
            test().await;
        });
    });
}

#[instrument]
async fn test() {
    let fut = async move {
        info!("Hello");
    };
    async_std::task::spawn(fut.in_current_span()).await;
}
```

I've not sure if it's eqaul to https://github.com/tokio-rs/tracing/issues/1102 so I opened. Please close it if it's some issue.

**Comment by hawkw** [comment]
I believe the issue is the following: `async_std::task::spawn` spawns the future on a worker thread in the `async_std` runtime, while `subscriber::with_default` sets the default subscriber for the _current_ thread. This means that when the spawned future is executed, it's outside of the context of the subscriber that was the default when the span was created. Instead, the global default is used, and that subscriber does not know about the span that was created with the `with_default` subscriber.

To solve this, you can explicitly propagate the current default subscriber context when spawning the future, using the [`with_current_subscriber` combinator](https://docs.rs/tracing/0.1.25/tracing/instrument/trait.WithSubscriber.html#method.with_current_subscriber). To do that, you would change the line of code where you call `task::spawn` to look like this:

```rust
    async_std::task::spawn(fut.in_current_span().with_current_subscriber()).await;
```

Hope that helps!

**Comment by lambdalisue** [comment]
Got it thanks :tada: I doubted `async-std` but I couldn't reached that point...

**Comment by lambdalisue** [comment]
:memo:

The `WithSubscriber` trait in [`tracing::instrument::WithSubscriber`](https://docs.rs/tracing/0.1.25/tracing/instrument/trait.WithSubscriber.html#method.with_current_subscriber) did not work but [`tracing_futures::WithSubscriber`](https://docs.rs/tracing-futures/0.2.5/tracing_futures/trait.WithSubscriber.html).
The difference is that the one in tracing-futures implements `impl<T: Sized> WithSubscriber for T`.
