### ISSUE TITLE
`Value` implementation for `dyn Error + 'static` prints first cause only

### ISSUE THREAD

**Issue by mbr** [tokio-rs/tracing#1347]
## Feature Request

When logging a `&std::error::Error` directly, only the first `.source()` is printed, as seen in [the example](https://gist.github.com/rust-play/282a7eadf3170c5f4ef33eb70338cb16). This should be changed to log all of them instead.

### Crates

Likely `tracing`, if changing the `tracing::Value` implementation.

### Motivation

It's pretty common to have errors that are fairly nondescript until one follows more than step up the source chain, so it would be good to have the underlying causes logged.

### Alternatives

Implement your own newtype wrapper with a `Display` impl.

Somewhat related: https://github.com/tokio-rs/tracing/issues/1308

**Comment by hawkw** [comment]
The issue here is in the default field formatter implementation for `tracing_subscriber::fmt`. If we look at these two lines:
https://github.com/tokio-rs/tracing/blob/1e09e50e8d15580b5929adbade9c782a6833e4a0/tracing-subscriber/src/fmt/format/mod.rs#L747-L748
we see that only the immediate source is formatted, and any subsequent sources are skipped.

We could fix this pretty easily by changing that code to format the whole source chain.

We should probably also change the delimiters for the source so that they match the way other fields are formatted. Right now, a macro invocation like 
```rust
tracing::info!(foo = "some field", err = error.as_ref());
```
foo="some field" err=error's display impl err: error's source's display impl
 ```
which is not consistent. we probably want something like 
```
foo="some field" err=error's display impl err.sources=[error's source's display impl, ...]
```
