### ISSUE TITLE
Void spans

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tracing#140]
### Crates

`tracing`

### Motivation

In `tokio-tower`, and elsewhere, I have cases where I may or may not want to include a `Span` with something like a request. For example, I want to trace only a certain subset of the requests. To do that, I currently have to keep an `Option<Span>` along with some code like:

```rust
let _guard = self.span.map(Span::enter);
```

### Proposal

The solution outlined above works okay, but it'd be nicer if there existed a sort of "void" `Span` that was free to produce, and that did nothing when entered. Ideally I would also not need to give `Metadata` for it, since it shouldn't ever be used.
```

**Comment by hawkw** [comment]
> ## Feature Request
> ### Crates
> 
> `tracing-core`?

I think this would be a change in `tracing` rather than `tracing-core`; the `Span` type is from `tracing` :)

> [...]
> The solution outlined above works okay, but it'd be nicer if there existed a sort of "void" `Span` that was free to produce, and that did nothing when entered. Ideally I would also not need to give `Metadata` for it, since it shouldn't ever be used.

I think we could implement this rather easily, actually. It could look like this: 
```rust
impl Span { 
    // ...
 
    pub fn none() -> Self {
        let meta = $crate::callsite! {
            name: "no span"
            kind: Kind::SPAN,
            target: ""
            level: Level::TRACE,
            fields: 
        }.metadata();
        Self {
            meta,
            inner: None,
        }
    }

    // ...
}
```
We could then hack the log support to not log for spans originating at the empty callsite.

We would need to make sure the documentation clearly distinguishes between `Span::new_disabled` and `Span::none`.

Name is, of course, open to bikeshedding.

**Comment by jonhoo** [comment]
> I think this would be a change in tracing rather than tracing-core; the Span type is from tracing :)

Updated!

**Comment by hawkw** [comment]
As an alternative, we could also move the metadata field optional. I think that might be the right approach. It'd make life easier for a `Span::current` function in the case that we're not currently in a span; otherwise, we'd have to return `Option<Span>`. And, since it's a reference, it shouldn't make the struct bigger to add an option.
