### ISSUE TITLE
tracing-journald 0.2.0 not published on crates.io and tag missing

### ISSUE THREAD

**Issue by marcelbuesing** [tokio-rs/tracing#1419]
### Version
0.2.0

### Crates

- tracing-journald

### Description

The [docs](https://tracing-rs.netlify.app/tracing_journald/) point to 0.2.0 but it appears there is no tag 0.2.0 for tracing-journald and no 0.2.0 version published to crates.io. I assume this might be because 0.2.0 was not ready yet, but there appear to have been quite a number of changes and no commits for some time.

**Comment by hawkw** [comment]
v0.2 is not published yet; the version number was bumped on `master` to track unreleased breaking changes in `tracing` and `tracing-core` which we're still working on.

If there are specific changes that you want published, they can be backported to v0.1.x and published, but looking at the Git history, there haven't been any significant code changes since the last released version. Is there a specific change I'm overlooking?

**Comment by marcelbuesing** [comment]
I think it was mostly confusion since the readme links to 0.2.0 docs for tracing-journald. No need to backport changes, thanks!
