### ISSUE TITLE
Tried to drop a ref to Id(_), but no such span exists!

### ISSUE THREAD

**Issue by TvoroG** [tokio-rs/tracing#1449]
### Version

```
├── tracing v0.1.26
│   ├── tracing-attributes v0.1.15 (proc-macro)
│   └── tracing-core v0.1.18
├── tracing-attributes v0.1.15 (proc-macro) (*)
├── tracing-futures v0.2.5
│   └── tracing v0.1.26 (*)
└── tracing-subscriber v0.2.19
    ├── tracing v0.1.26 (*)
    ├── tracing-core v0.1.18 (*)
    ├── tracing-log v0.1.2
    │   └── tracing-core v0.1.18 (*)
    └── tracing-serde v0.1.2
        └── tracing-core v0.1.18 (*)
```
### Platform

`Linux 5.10.40 x86_64`

### Description

Hi! Thank you for your work!

Here is a code to reproduce the panic:
```rust
use tracing_futures::WithSubscriber;
use tracing_subscriber;
use tracing_attributes::instrument;

#[tokio::main]
pub async fn main() {
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::INFO)
        .init();

    let _ = tokio::task::spawn(do_work()).await;
    let _ = tokio::task::spawn(do_work_with_new_subscriber()).await;
    let _ = tokio::task::spawn(do_work()).await;
}

#[instrument]
async fn do_work() {
    tokio::time::sleep(tokio::time::Duration::from_millis(1)).await;
}

async fn do_work_with_new_subscriber() {
    let subscriber = tracing_subscriber::fmt()
        .with_max_level(tracing::Level::TRACE)
        .finish();

    let dispatch = tracing::dispatcher::Dispatch::new(subscriber);

    let _dis_entered = tracing::dispatcher::set_default(&dispatch);

    let fut = do_work();

    let _ = fut.with_current_subscriber().await;
}
``` 
It's not always panicking, but keep trying.

What am i doing wrong?

**Comment by hawkw** [comment]
The issue here is due to the use of `dispatcher::set_default` in an `async fn`. `set_default` returns a drop guard that unsets the current dispatcher when it's dropped. However, when an asynchronous task yields, local variables in that task are _not_ dropped. Then, when the task yields, the executor polls a task with a span created in the previous subscriber's context, causing the current subscriber to see a span ID which it doesn't recognize.

The docs for the `Span::enter` method [describe a similar issue with using that API in `async fn`s](https://docs.rs/tracing/0.1.26/tracing/span/struct.Span.html#in-asynchronous-code); they may be helpful for understanding what's happening here in greater detail. We should probably add a similar note to the documentation for `dispatcher::set_default`.

Similarly to how `tracing::Instrument` provides an `instrument` combinator for attaching a span to an `async fn`, the [`tracing-futures` crate](https://lib.rs/crates/tracing-futures) provides [a `WithSubscriber` combinator](https://docs.rs/tracing-futures/0.2.5/tracing_futures/trait.WithSubscriber.html). This should be used for attaching a subscriber to an `async fn` in place of `set_default`.

Hope that description of the problem is helpful --- and we should definitely add a note to the documentation for `set_default`!

**Comment by TvoroG** [comment]
Thanks a lot for your help! `WithSubscriber` works very well.

**Comment by hawkw** [comment]
Great, glad everything is working now! I'll make sure to add a note in the docs so others can avoid this problem in the future.
