### ISSUE TITLE
Can't get tracing-futures to work in my codebase

### ISSUE THREAD

**Issue by singpolyma-shopify** [tokio-rs/tracing#169]
### Version

```
$ cargo tree | grep tracing
├── tracing v0.1.2
│   └── tracing-core v0.1.1
├── tracing-fmt v0.1.0 (https://github.com/tokio-rs/tracing#41738445)
│   └── tracing-core v0.1.1 (*)
├── tracing-futures v0.0.1 (https://github.com/tokio-rs/tracing#41738445)
│   └── tracing v0.1.2 (*)
```

### Platform

`$ uname -a
Linux singpolyma-crappy-internal 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux`

### Description

I cannot get tracing-fmt and tracing-futures to output anything at all.  I even copied the example code for spawny-thing into my app (commenting out my `main` and using the one from the example) and it compiles but there is no output.  Doing the same thing with a `tracing` examples that doesn't use tokio or futures works fine, so anything works at all.  My guess is that the subscriber is somehow not following into the tokio threadpool properly.

**Comment by hawkw** [comment]
@singpolyma-shopify What version of `tokio` are you using? You probably either need to set the feature flag `experimental-tracing` on your `tokio` dependency, or use [`dispatcher::set_global_default`](https://docs.rs/tracing/0.1.2/tracing/dispatcher/fn.set_global_default.html) rather than `with_default`.

Let me know if either of those fix the problem for you?

**Comment by singpolyma-shopify** [comment]
@hawkw Thanks! Adding the feature fixed it for me.

**Comment by hawkw** [comment]
Great! I'll make sure to add this to the documentation to hopefully avoid any future confusion!
