### ISSUE TITLE
Events now unfiltered for fmt::writer::Boxed's MakeWriter impl

### ISSUE THREAD

**Issue by estk** [tokio-rs/tracing#1694]
## Bug Report

I found that events are no longer sorted when contained in the fmt::writer::Boxed, here's the [diff](https://github.com/tokio-rs/tracing/compare/tracing-subscriber-0.2.25...tracing-subscriber-0.3.1#diff-c5dc275b15a60c1a2d4694da3797f4247c4f2e1e0978fd210dd14452d6746283L737)

### Version

change from 0.2.25 to 0.3.1

### Platform

x86_64-apple-darwin
rustc 1.57.0-nightly (9dbb26efe 2021-10-03)

### Description

I have tests which verify the content of tracing output to either contain or not contain events based on the level. As of 0.3.1 events are completely unfiltered.

**Comment by hawkw** [comment]
Ah, I see what happened here. It looks like in commit 6cc6c47354ceeb47da7c95faa41c6d29b71b5f37, which backported the change to add a lifetime parameter to `MakeWriter` (#781), I accidentally clobbered the `make_writer_for` method on `BoxWriter`, so that it only has `make_writer`: https://github.com/tokio-rs/tracing/commit/6cc6c47354ceeb47da7c95faa41c6d29b71b5f37#diff-c5dc275b15a60c1a2d4694da3797f4247c4f2e1e0978fd210dd14452d6746283L737-L739

this means that any filtering performed by the `MakeWriter` inside the box is now ignored. My bad!

Fortunately, fixing this is as simple as...putting the method back. Should have it taken care of momentarily!

**Comment by hawkw** [comment]
Fixed by #1695!
