### ISSUE TITLE
tracing-subscriber 0.3.x releases don't have changelog entries

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/tracing#1732]
I would expect to be able to read sth. about about those releases in [this changelog](https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/CHANGELOG.md).

**Comment by hawkw** [comment]
They're on the [`v0.1.x` branch](https://github.com/tokio-rs/tracing/blob/v0.1.x/tracing-subscriber/CHANGELOG.md), which tracks the current state of the released `tracing` 0.1.x ecosystem. The `master` branch is a development branch for the upcoming v0.2.x ecosystem.

**Comment by jplatte** [comment]
How could I have discovered this on my own? Couldn't you copy the changelog entries over?

**Comment by hawkw** [comment]
We could start doing that. Alternatively, though, I think the best solution is to change the repository's default branch to `v0.1.x`, until `tracing` 0.2 is ready to release. That way, it would be the first thing you see on the GitHub repo. I've been considering doing this for a while, as 0.2 development has dragged on for a while (largely due to upstream dependency issues).

Note that the changelog entries should also be published to [GitHub releases](https://github.com/tokio-rs/tracing/releases), though, so you can also check there.
