### ISSUE TITLE
tracing-journald:  Do not connect socket

### ISSUE THREAD

**Issue by lunaryorn** [tokio-rs/tracing#1745]
## Bug Report

Currently tracing-journald subscribers immediately connect to the systemd journal socket.

I believe this implies that the subscriber will permanently fail if the connection to the socket ever drops, e.g. if journald crashes.  I think the subscriber should use an unconnected socket and then use `send_to` to specify the target socket explicitly for every message.  That'd make a subscriber "survive" a journald crash, and it's also what [upstream does](https://github.com/systemd/systemd/blob/main/src/libsystemd/sd-journal/journal-send.c#L213)

I can make a pull request (based on #1744) to change this.

### Crates

tracing-journald

**Comment by Ralith** [comment]
SGTM!

**Comment by Ralith** [comment]
Actually, one drawback to this: if we don't `connect` at startup, we lose the immediate, actionable feedback on journald being missing/misconfigured/whatever. This isn't a problem for upstream because they propagate errors to the user, but a tracing subscriber can't. Surviving a journald restart is still a huge win, but we should probably at least check that `/run/systemd/journal/socket` exists and is writable in `new`.
