### ISSUE TITLE
Panic when using JSON format and `#[instrument]`

### ISSUE THREAD

**Issue by gahag-cw** [tokio-rs/tracing#1776]
### Version

```
├── tracing v0.1.29
│   ├── tracing-attributes v0.1.18 (proc-macro)
│   └── tracing-core v0.1.21
└── tracing-subscriber v0.3.3
    ├── tracing-core v0.1.21 (*)
    ├── tracing-log v0.1.2
    │   └── tracing-core v0.1.21 (*)
    └── tracing-serde v0.1.2
        └── tracing-core v0.1.21 (*)
```

### Platform

`Linux 5.10.84-1-lts #1 SMP Wed, 08 Dec 2021 10:17:01 +0000 x86_64 GNU/Linux`
### Crates

- `tracing-subscriber`

### Description

When using the JSON format in conjunction with the `#[instrument]` macro, we get a panic.

Minimal code:
```Rust
fn main() {
    tracing_subscriber::fmt()
        .event_format(tracing_subscriber::fmt::format().json())
        .init();

    test("hai")
}

#[tracing::instrument]
fn test(input: &str) {
    tracing::info!("got: {}", input);
}
```

Which results in:
```
thread 'main' panicked at 'span 'test' had malformed fields! this is a bug.
  error: expected value at line 1 column 1
  fields: FormattedFields { fields: "input=\"hai\"", formatter: tracing_subscriber::fmt::format::DefaultFields }', ~/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.0/src/fmt/format/json.rs:166:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
If we comment the `#[tracing::instrument]` line, it works as expected.

**Comment by davidbarsky** [comment]
Sorry for the delay and the fact that you encountered this issue. The issue is the same as https://github.com/tokio-rs/tracing/issues/1365; you'll also need add a JSON-specific field formatter, which is needed to record span fields (in reproduction, that would be `input`).

```rust
tracing_subscriber::fmt()
    .event_format(tracing_subscriber::fmt::format().json())
    .fmt_fields(tracing_subscriber::fmt::format::JsonFields::new())
    .init();
```

An alternative would be to use the [`.json()` builder method](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.json) on `fmt::SubscriberBuilder`:

```rust
tracing_subscriber::fmt()
    .json()
    .init();
```
