### ISSUE TITLE
Tracking "current spans" under tokio

### ISSUE THREAD

**Issue by singpolyma-shopify** [tokio-rs/tracing#188]
Just thinking through how this works, reading  the tracing-fmt code -- it  seems like "current spans" is tracked per-thread by using thread-local storage.  But can this approach work in a tokio/async/futures application?  If a span is entered as a future starts, then that future blocks on IO and another future is scheduled on the thread and logs an event -- won't the first span still be "entered" even if this event is from a completely different workload?

**Comment by hawkw** [comment]
If spans are attached to futures using the [`Instrument`](https://github.com/tokio-rs/tracing/blob/2cfc5130b64242a22b085ca06aa40e74c429a784/tracing-futures/src/lib.rs#L32) combinator in the `tracing-futures` crate, then the span will be entered only for the duration of each poll, and exited when the poll ends (i.e. the future yields). Then, when the future completes, the span will be dropped and (if it's the only reference to the span with that ID) the span will close.

This is why `tracing`'s concept of `enter`ing and `exit`ing a span is distinct from creating and closing a span. In particular, to nicely support asynchronous code, _entering_ a span must be able to be scoped to a function call, but the overall lifetime of the span must be able to persist across function calls.

As a side note, future plans include a `spawn!` macro for automatically instrumenting spawned futures, and adding support for async functions to the `#[trace]` attribute macro so that async functions get the same behaviour as instrumented futures.

**Comment by singpolyma-shopify** [comment]
Ok, I see.  I thought a span could be entered/exited multiple times so you could share a span definition, but it seems the expectation is to `new_span` when starting an instrumented something and `drop_span` when finishing it and enter/exit is for tracking current state in the middle specifically for the async case?

**Comment by hawkw** [comment]
More or less, yes! I wouldn't go so far as to say that `enter`/`exit` is _specifically_ for async, though

Even in synchronous code you might have, say some struct that does some part of the work for the system, and you might want to track the period of time that was spent on each of those units of work. In that  case, you might want to have a single span for each instance of that struct, and enter that span whenever methods are called on that struct.

**Comment by hawkw** [comment]
In re:
>  I thought a span could be entered/exited multiple times so you could share a span definition

It's worth noting that there's a difference between two spans that share a _callsite_, and two handles to a span with the same `Id`. A span `Id` is intended to represent a single span in time, whereas two spans sharing a callsite share a definition but represent discrete periods of time.
