### ISSUE TITLE
tracing-subscriber: EnvFilter::try_from_default_env() returns Ok for any RUST_LOG value

### ISSUE THREAD

**Issue by SzudemJ** [tokio-rs/tracing#2104]
### Version

```bash
cargo tree | grep tracing
│   │   │   │   └── tracing v0.1.34
│   │   │   │       ├── tracing-attributes v0.1.21 (proc-macro)
│   │   │   │       └── tracing-core v0.1.26
│   │   │   └── tracing v0.1.34 (*)
│   │   ├── tracing v0.1.34 (*)
│   │   └── tracing v0.1.34 (*)
│   │   └── tracing v0.1.34 (*)
├── tracing v0.1.34 (*)
├── tracing-appender v0.2.2
│   └── tracing-subscriber v0.3.11
│       ├── tracing v0.1.34 (*)
│       ├── tracing-core v0.1.26 (*)
│       ├── tracing-log v0.1.3
│       │   └── tracing-core v0.1.26 (*)
│       └── tracing-serde v0.1.3
│           └── tracing-core v0.1.26 (*)
├── tracing-log v0.1.3 (*)
├── tracing-subscriber v0.3.11 (*)
```
### Platform

Darwin Users-MBP 20.6.0 Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64 x86_64

### Crates

tracing-subscriber

### Description

First of all, thank you for this incredible work!

EnvFilter::try_from_default_env() returns Ok for any RUST_LOG value.
This results in my programm not showing any logs if the value of RUST_LOG is actually an invalid filter directive as it is not handling the error case.

I tried this code:
```rust
pub fn get_tracing_filter(level: &str) -> EnvFilter {
    EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new(level))
}
```

With different values for RUST_LOG:
```bash
cargo run # this shows tracing logs as configured in my app settings
RUST_LOG= cargo run # this shows no logs
RUST_LOG=bla cargo run # this shows no logs
RUST_LOG=info cargo run # this shows info-level tracing logs
```

According to the [documentation](https://docs.rs/tracing-subscriber/0.3.11/tracing_subscriber/struct.EnvFilter.html#method.try_from_default_env) the Result of EnvFilter::try_from_default_env() should be an Error:
> if the environment variable is unset or contains any invalid filter directives

I tried to learn more about the Result using this code:
```rust
pub fn get_tracing_filter(_level: &str) -> EnvFilter {
    let res = EnvFilter::try_from_default_env(); //.unwrap_or_else(|_| EnvFilter::new(level))
    println!("{:?}", res);

    EnvFilter::default()
}
```

With different values for RUST_LOG:
```bash
cargo run
Err(FromEnvError { kind: Env(NotPresent) })

RUST_LOG= cargo run
Ok(EnvFilter { statics: DirectiveSet { directives: [], max_level: LevelFilter::OFF }, dynamics: DirectiveSet { directives: [], max_level: LevelFilter::OFF }, has_dynamics: false, by_id: RwLock { data: {}, poisoned: false, .. }, by_cs: RwLock { data: {}, poisoned: false, .. }, scope: ThreadLocal { local_data: None }, regex: true })

RUST_LOG=bla cargo run
Ok(EnvFilter { statics: DirectiveSet { directives: [StaticDirective { target: Some("bla"), field_names: [], level: LevelFilter::TRACE }], max_level: LevelFilter::TRACE }, dynamics: DirectiveSet { directives: [], max_level: LevelFilter::OFF }, has_dynamics: false, by_id: RwLock { data: {}, poisoned: false, .. }, by_cs: RwLock { data: {}, poisoned: false, .. }, scope: ThreadLocal { local_data: None }, regex: true })

RUST_LOG=info cargo run
Ok(EnvFilter { statics: DirectiveSet { directives: [StaticDirective { target: None, field_names: [], level: LevelFilter::INFO }], max_level: LevelFilter::INFO }, dynamics: DirectiveSet { directives: [], max_level: LevelFilter::OFF }, has_dynamics: false, by_id: RwLock { data: {}, poisoned: false, .. }, by_cs: RwLock { data: {}, poisoned: false, .. }, scope: ThreadLocal { local_data: None }, regex: true })
```

According to the [documentation](https://docs.rs/tracing-subscriber/0.3.11/tracing_subscriber/struct.EnvFilter.html#method.try_from_default_env) and also due to the naming of the method, I expected an Error when RUST_LOG= or RUST_LOG=bla.

**Comment by hawkw** [comment]
All of the sample inputs you've used are currently considered valid filter strings.

`RUST_LOG="bla"` is a valid directive because a target is passed without a `={LEVEL}` component is interpreted as enabling the `TRACE` level for that target, so `RUST_LOG="bla"` is equivalent to writing `RUST_LOG="bla=trace"`. See https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#usage-notes. That directive prints no logs because there aren't actually any targets named "bla" in your program, but there isn't really a way for `EnvFilter` to know that when it's parsed, as we can't enumerate a list of all targets in the program up front.

The totally empty filter string is also currently treated as valid and simply falls back to the [default directive](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.Builder.html#method.with_default_directive). We could certainly consider changing this behavior for the `try_` family of parsing functions, but I'm not sure if that's what everyone would want here.

The `try_from_default_env` function (and similar functions) will only emit an error if there's a directive that contains syntax errors. For example, if there's an `=` component followed by something that's not a level, like `RUST_LOG="bla=bleh"`, that would emit an error.

**Comment by SzudemJ** [comment]
thanks, @hawkw. that makes actual sense. I guess I was just not familiar with options for RUST_LOG.
I am going to close this.
