### ISSUE TITLE
Add support for `Option<impl Display>` values.

### ISSUE THREAD

**Issue by BratSinot** [tokio-rs/tracing#2142]
### Motivation
Currently, we are able to use optional fields like this:
```rust
info!(opt = Option::<u32>::None, "none");
info!(opt = Option::<u32>::Some(123), "Some");
```

But we can't use it for values without `trait Value` implemented, but `trait Display`, for example `Uuid` crate:
```rust
    let id = Uuid::new_v4();

    info!(opt = %Option::<&Uuid>::None, "None");
    info!(opt = %Option::<&Uuid>::Some(&id), "Some");
```

And I can't implement `Value` for wrapper, because of `Sealed`.

**Comment by BratSinot** [comment]
Em, okey, latest `tracing-core` missing this:
```rust
impl<T: Value> Value for Option<T> {
    fn record(&self, key: &Field, visitor: &mut dyn Visit) {
        if let Some(v) = &self {
            v.record(key, visitor)
        }
    }
}
```

And I can't use old code....

**Comment by hawkw** [comment]
> But we can't use it for values without `trait Value` implemented, but `trait Display`, for example `Uuid` crate:
> 
> ```rust
>     let id = Uuid::new_v4();
> 
>     info!(opt = %Option::<&Uuid>::None, "None");
>     info!(opt = %Option::<&Uuid>::Some(&id), "Some");
> ```

I think the problem here is that `Uuid` implements `fmt::Display`, but it doesn't implement the `tracing::field::Value` trait. You should be able to use `Option<&Uuid>` as a field value in this case by mapping the inner value to a `dyn Display` *trait object*, which does implement `tracing::field::Value`. Something like this should work:
```rust
    let id = Uuid::new_v4(); 
    let opt = Some(&id);

    info!(opt = Option::<&dyn fmt::Display>::None, "None");
    info!(opt =  id.map(tracing::field::display), "Some");
```



> Em, okey, latest `tracing-core` missing this:
> 
> ```rust
> impl<T: Value> Value for Option<T> {
>     fn record(&self, key: &Field, visitor: &mut dyn Visit) {
>         if let Some(v) = &self {
>             v.record(key, visitor)
>         }
>     }
> }
> ```
> 
> And I can't use old code....

That implementation should be present for the latest release version of `tracing`, on the `v0.1.x` branch: https://github.com/tokio-rs/tracing/blob/c744b2f8bebfd7b53a454096aa7044cf12df4802/tracing-core/src/field.rs#L708-L716

The `master` branch is an in-development branch for the upcoming `tracing` 0.2.0 release; you probably shouldn't be using it.The `v0.1.x` branch contains up-to-date code for the latest version.
