### ISSUE TITLE
Upgrade `tokio` dependency in `tracing-futures`.

### ISSUE THREAD

**Issue by Narsil** [tokio-rs/tracing#2394]
### Crates

`tracing-future` 

### Motivation

We are adding opentelemetry in our project, and `cargo audit` started flagging some of the crates.
It all stem from  `tracing-future` optional `tokio` dependency which is `0.1.22`.
https://github.com/tokio-rs/tracing/blob/master/tracing-futures/Cargo.toml#L36

### Proposal

Shouldn't it be `1.22` instead ? (at least a recent version).

### Alternatives

We fixed in on our end by avoiding the feature. altogether

@OlivierDehaene

**Comment by davidbarsky** [comment]
No, the presence of Tokio 0.1 inside of  `tracing-futures` is intentional, as it provides support for Tokio 0.1. Features that would otherwise be gated behind a Tokio 1.0 flag inside of `tracing-futures` are instead gated by the [`tokio_unstable`](https://docs.rs/tokio/latest/tokio/#unstable-features) flag. At the moment, I don't expect that we'll add a Tokio 1.0 flag to `tracing-futures` because we'd rather integrate into Tokio directly.
