### ISSUE TITLE
A tool for `tracing::instrument`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [tokio-rs/tracing#2627]
### Crates

`tracing`

### Motivation

I work on a large project with >3500 functions, I do not want to go through all of these adding `tracing::instrument`.

### Proposal

I made a tool (https://github.com/JonathanWoollett-Light/clippy-tracing) that can:

- Add `tracing::instrument` to all functions.
- Remove `tracing::instrument` from all functions.
- Check if any functions are missing `tracing::instrument`.

This significantly helps (and I would argue is even necessary) to integrate `tracing` in a large project.

This tool should be an official crate and can greatly improve the developer experience.

### Alternatives

I'm not aware of any alternative.

**Comment by hawkw** [comment]
Hi @JonathanWoollett-Light, this is very cool! I think your tool will definitely be useful to a lot of `tracing` users!

At this time, we are trying to avoid adding any new crates to the `tokio-rs/tracing` repository (and are in the process of moving some crates that don't strictly need to be in this repo into their own repos). This is in order to reduce the maintenance burden in this repo --- for example, CI builds in this repository are currently quite slow as they have to build a large number of crates. It seems like your tool doesn't really need to be in the `tokio-rs/tracing` git repo, as it doesn't directly depend on any `tracing` crates and shouldn't need tight integration testing with changes to `tracing` and `tracing-core`. Therefore, I think development on both `tracing` and `clippy-tracing` will probably be able to move much faster if we keep them in separate git repositories.

However, we'd be very happy to add links to your crate to the `tracing` documentation. To start, there's a list of related crates in the `tracing` documentation, here: https://github.com/tokio-rs/tracing/blob/ebd437cf1a1f4bb3f916cde7d798776b89e319cb/tracing/src/lib.rs#L745-L813
We should definitely add `clippy-tracing` to that list. I would also be happy to accept PRs that mention the use of your tool in the documentation for the `#[tracing::instrument]` macro, and in various "getting started" guides such as https://tokio.rs/tokio/topics/tracing. 

If your tool starts getting widespread adoption by users, we would definitely also be open to making it an "official" tracing project by moving it into the `tokio-rs` github organization, in its own repository (`tokio-rs/clippy-tracing`?). If we do that, it would be helpful if you would assume some of the responsibility for maintaining the project after its moved into the `tokio-rs` organization.

**Comment by JonathanWoollett-Light** [comment]
Posted a PR adding it to the documentation https://github.com/tokio-rs/tracing/pull/2628.
