### ISSUE TITLE
Make `Span::{enter, entered}` `must_use`

### ISSUE THREAD

**Issue by tgross35** [tokio-rs/tracing#2729]
## Feature Request

It seems like `enter` and `entered` could be `#[must_use]` to indicate that the handle needs to be assigned to something to have an effect. There may be other functions that could benefit from this.

### Motivation

If the result of these functions is not assigned to a variable, the guard will be dropped immediately. This means the span never gets entered, which is a mistake and can lead to confusing “why isn’t this logging” errors.

### Proposal

Mark these functions `#[must_use]` which should warn if the span isn’t entered.

**Comment by kaffarell** [comment]
The return values of `enter` and `entered` (respectively `Entered` and `EnteredSpan`) are already marked with `#[must_use(..)]`, so the following code example will return an warning:
```rust
let test = span!(Level::INFO, "test");
test.enter();
```
Output:
```
   Compiling rust_test v0.1.0 (/home/ggoller/Desktop/rust_test)
warning: unused `Entered` that must be used
 --> src/main.rs:5:5
  |
5 |     test.enter();
  |     ^^^^^^^^^^^^
  |
  = note: once a span has been entered, it should be exited
  = note: `#[warn(unused_must_use)]` on by default
help: use `let _ = ...` to ignore the resulting value
  |
5 |     let _ = test.enter();
  |     +++++++

warning: `rust_test` (bin "rust_test") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
     Running `target/debug/rust_test`

```

**Comment by hawkw** [comment]
In cases like this, it's preferable to place `#[must_use]` attributes on the type, rather than on functions returning that type.

This is because a function with `#[must_use]` only conveys that the return value of *that function* must be used --- if I write code that wraps a call to a function with `#[must_use]` on it and returns the return value of the `#[must_use]` function, the return value of _my_ function will not emit `#[must_use]` warnings. On the other hand, if the type itself is `#[must_use]`, any downstream code which constructs an `Entered` or `EnteredSpan` guard using `Span::enter`/`Span::entered` and returns that guard will _also_ result in warnings if the guard is not used by the caller, without requiring that the wrapper function also be annotated with `#[must_use]`.

Since there are already `#[must_use]` attributes on these types, I'm going to close this issue.

**Comment by tgross35** [comment]
Hm, I wasn't getting the warnings for some reason. Oh well, thanks for clarifying!
