### ISSUE TITLE
`info!`/`error!`/`warn!` macros don't accept constants for first field name

### ISSUE THREAD

**Issue by tim3z** [tokio-rs/tracing#2837]
### Version

```
tracing v0.1.40
    ├── tracing-attributes v0.1.27 (proc-macro)
    └── tracing-core v0.1.32
```

### Platform

macOS 13.6
`Darwin HAMACL00492 22.6.0 Darwin Kernel Version 22.6.0: Tue Nov  7 21:40:08 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_ARM64_T6000 arm64`

```
stable-aarch64-apple-darwin (default)
rustc 1.74.1 (a28077b28 2023-12-04)
```

### Description

I expected the following sample to compile. The problem is the same on all the different log levels (I tried only info, warn and error)

```rust
const FOO: &str = "foo";
fn main() {
    tracing::info!(bar = 42, { FOO } = 23, "tada"); // works
    tracing::event!(tracing::Level::INFO, { FOO } = 23, bar = 42, "tada"); // works, too
    tracing::info!({ FOO } = 23, bar = 42, "tada"); // doesn't compile
}
```

**Comment by ItsEthra** [comment]
I don't think they should compile. The same behavior is present in `println`, `format`, etc. Because those macros accept a string literal. Also I believe `info`, `warn`, `error`, etc all use `format_args` internally which also requires a string literal so it just wouldn't be possible.

**Comment by mladedav** [comment]
This should compile, the [docs](https://docs.rs/tracing/latest/tracing/index.html#recording-fields) say that you can use constant expressions as names. There just seems to be an issue with it being the first field because `{ ... }` is already handled specially.

There's a [test](https://github.com/tokio-rs/tracing/blob/master/tracing/tests/event.rs#L407) for this, it just doens't use the constant in the first position so this should probably be expanded and then fixed.
