### ISSUE TITLE
alternate debug macro syntax e.g. `info!({ ?#field }, "...")`

### ISSUE THREAD

**Issue by anp** [tokio-rs/tracing#289]
### Crates

tracing-fmt

### Motivation

A concise improvement to legibility of `Debug` fields.

### Proposal

Add another syntax option to the tracing macros.

### Alternatives

The main alternative I see would be to use a specially configured fmt::Formatter to somehow allow subscribers to decide how to present the contents, but I don't think that's feasible based on my understanding of format_args.

**Comment by hawkw** [comment]
:+1: Definitely in favor of adding this. I've punted on it thus far just because nobody had asked for it yet.

I think adding a `field::debug_alt` (name TBD) and shorthand in the macros should be fairly straightforward.  I think that ideally, the decision of whether to use the single-line or alternate debug formatting ought to be left up to the subscriber, but I'll have to look into whether that's possible.

**Comment by hawkw** [comment]
After some experimentation, I don't think this is necessary --- when presented with a `&dyn fmt::Debug` in `Visit::record_debug`, the visitor absolutely can choose to use the default formatting. 

https://github.com/tokio-rs/tracing/pull/241/commits/780898d3c5d2cb2b4a5968ce429d367edcf2a4e5 adds a `MakeVisitor` wrapper in `tracing-subscriber` that wraps a visitor so that it formats all `Debug` fields using `{:#?}`.

**Comment by hawkw** [comment]
> After some experimentation, I don't think this is necessary --- when presented with a `&dyn fmt::Debug` in `Visit::record_debug`, the visitor absolutely can choose to use the default formatting.

@anp given ☝️, do you think there's still a need for specifying the alternative format in the instrumentation point (read: the macros) as well as in the subscriber?

**Comment by carllerche** [comment]
What does the syntax mean?

**Comment by carllerche** [comment]
i assume `field` here is some local ident?

**Comment by carllerche** [comment]
My gut is formatting syntax would be less weird if it were in a string:

```rust
let value = MyValue::new();
info!("hello", "{:#value}");
```

**Comment by anp** [comment]
> > After some experimentation, I don't think this is necessary --- when presented with a `&dyn fmt::Debug` in `Visit::record_debug`, the visitor absolutely can choose to use the default formatting.
> 
> @anp given ☝️, do you think there's still a need for specifying the alternative format in the instrumentation point (read: the macros) as well as in the subscriber?

No, I think that's perfect, and avoids complicating the syntax. Given the visitor-based formatting that landed I'll give this a close.
