### ISSUE TITLE
metrics: Introduce `tracing-metrics` subscriber/crate

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/tracing#29]
This is a tracking issue for introducing a new `tokio-trace-metrics` crate that will contain a metrics-based subscriber and traits that metrics providers can implement:

- [ ] Create a `Metrics` subscriber
- [ ] Provide a `Metrics` agnostic backend trait

**Comment by hawkw** [comment]
The first question I have is whether or not we want to have a `tokio-trace-metrics` crate or just crates for particular metrics systems (`tokio-trace-prometheus`, `tokio-trace-influxdb`, and so on).

 I think this basically depends on how many common concepts there are between various metrics systems --- how much can we actually abstract away? If the metrics systems we want to support has concepts of metric names, labels/scopes, and types that differ significantly, there may not be enough common ground to be actually useful. 

I know [`hotmic`](https://docs.rs/hotmic/0.7.1/hotmic/) generalizes multiple metrics systems, so it's quite possible that there's enough commonality for a `tokio-trace-metrics` crate as well, but it just seems worth mentioning.

Designing a `Metrics` trait will definitely require some thought to come up with an interface flexible enough to abstract over various metrics libraries and over various metrics systems. It might be worth putting together a few prototype implementations for various backends _before_ we write the common abstraction layer, so that we can feel out the commonalities in a bottom-up way...

**Comment by LucioFranco** [comment]
@hawkw great points!

So I think _most_ metrics are roughly the same counters, gauges, histograms etc. Though I think you do have a good point that we shouldn't jump into a trait right away. What I think the best path forward right now then would be to build a basic general metrics subscriber, that is based on hotmic. Then use it as a platform to explore how other metric systems could be built. For Prometheus and Influx I'd like to stay away from those for the moment and focus on collecting since they mostly have similar concepts and its just about implementing their protocol.

**Comment by hawkw** [comment]
I'm tagging @tobz because I think he's expressed interest in this as well.

**Comment by MattesWhite** [comment]
Isn't this issue resolved by having the [`metrics` feature](https://github.com/tokio-rs/tracing-opentelemetry#feature-flags) in tracing-opentelemetry?

**Comment by hawkw** [comment]
@MattesWhite This issue was originally about having "some kind of metrics system" for `tracing`. Now that we have both metrics support in `tracing-opentelemetry` and integration with the [`metrics` crate ecosystem](https://docs.rs/metrics/0.21.1/metrics/) via [`metrics-tracing-context`](https://docs.rs/metrics-tracing-context/0.14.0/metrics_tracing_context/), I think it's probably fine to close this issue.
