### ISSUE TITLE
Regression for macro stack use in 0.1.6

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tracing#303]
#288 seems to have caused the `log` feature to break unexpectedly.
`Cargo.toml`:
```toml
[dependencies]
tracing = { version = "0.1.6", features = ["log"] }
```
`src/main.rs`
```rust
fn main() {
    tracing::event!(tracing::Level::TRACE, "retry sending request to Sink");
}
```
```console
$ cargo check
    Checking xx v0.1.0 (/home/jon/tmp/xx)
error: recursion limit reached while expanding the macro `$crate::__mk_format_args`
 --> src/main.rs:2:5
  |
2 |     tracing::event!(tracing::Level::TRACE, "retry sending request to Sink");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: consider adding a `#![recursion_limit="256"]` attribute to your crate
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
This code works fine when compiled against `0.1.5`, and git bisection shows that #288 is to blame.

**Comment by hawkw** [comment]
These macro compilation tests _should_ have caught this regression:
https://github.com/tokio-rs/tracing/blob/83aa04cc9e22fa61903478e0c983097788142e1d/tracing/tests/macros.rs#L270-L271

And indeed, it looks like a local `cargo test -p tracing --all-features` does catch this: 
```
:; cargo test -p tracing --all-features
   Compiling tracing v0.1.6 (/Users/eliza/Code/tracing/tracing)
error: recursion limit reached while expanding the macro `$crate::__mk_format_args`
   --> tracing/examples/counters.rs:130:9
    |
130 |         info!(yak_shaved = true, yak_count = 1, "hi from inside my span");
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider adding a `#![recursion_limit="256"]` attribute to your crate
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

error: Could not compile `tracing`.
warning: build failed, waiting for other jobs to finish...
error: recursion limit reached while expanding the macro `$crate::__mk_format_args`
  --> tracing/examples/sloggish/main.rs:34:9
   |
34 |         debug!(length = 2, "message received");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: consider adding a `#![recursion_limit="256"]` attribute to your crate
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

error: recursion limit reached while expanding the macro `$crate::__mk_format_args`
  --> tracing/tests/event.rs:86:9
   |
86 |         debug!(answer = 42, question, "hello from {where}! tricky? {:?}!", true, where = "my event");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: consider adding a `#![recursion_limit="256"]` attribute to your crate
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: Could not compile `tracing`.
warning: build failed, waiting for other jobs to finish...
error: aborting due to previous error

error: Could not compile `tracing`.
warning: build failed, waiting for other jobs to finish...
error: recursion limit reached while expanding the macro `$crate::__mk_format_args`
   --> tracing/tests/macros.rs:270:5
    |
270 |     event!(Level::DEBUG, "foo");
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider adding a `#![recursion_limit="256"]` attribute to your crate
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

error: Could not compile `tracing`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

It looks like these tests are not running on CI with the `log` feature enabled, which implies to me that our CI is misconfigured.

The actual bug looks like an oversight on my part (which wasn't caught because CI isn't running the tests with the appropriate feature flags), and should be pretty simple to fix.

Thanks for catching this @jonhoo!

**Comment by jonhoo** [comment]
I believe CI doesn't run this because we couldn't run with `--all-features` for some other reason?

**Comment by jonhoo** [comment]
@hawkw specifically, see https://github.com/tokio-rs/tracing/pull/191#issuecomment-513872071

**Comment by jonhoo** [comment]
We turn off checking all features here:
https://github.com/tokio-rs/tracing/blob/83aa04cc9e22fa61903478e0c983097788142e1d/azure-pipelines.yml#L10
Based on https://github.com/tokio-rs/tracing/pull/191#issuecomment-513872071, I think the issue was that we can't run with `--all-features` except on nightly. The easiest fix for this is probably to add a specific check with all features on nightly as you do in the related PR.

**Comment by hawkw** [comment]
@jonhoo 
> Based on [#191 (comment)](https://github.com/tokio-rs/tracing/pull/191#issuecomment-513872071), I think the issue was that we can't run with `--all-features` except on nightly. 

Right, it is specifically `tracing-futures` that cannot be tested on stable with `--all-features`.

> The easiest fix for this is probably to add a specific check with all features on nightly as you do in the related PR.

That's not actually what I've done in the PR --- I actually added a `cargo test --all-features -p tracing` job, which runs on stable. 

We _can_ also add a `check --all-features` job that checks all crates with `--all-features` on nightly; I thought it was better to check specifically the `tracing` crate on stable, because I'm still pretty leery of making any nightly-only CI job _required_ — I've seen enough breakage from nightly compiler regressions that I'd rather treat nightly as informational whenever possible.
