### ISSUE TITLE
Add an option for outputting span IDs

### ISSUE THREAD

**Issue by jwodder** [tokio-rs/tracing#3036]
### Crates

tracing-subscriber

### Motivation

When working with tracing logs from an async process — particularly one in which it's possible for there to be multiple spans with equal non-ID fields active at once in separate threads — it would be really useful if there was an option for making the output produced by `tracing-subscriber` include the span IDs so that individual log messages could be associated with the appropriate span and thus with other log messages in the same span.

### Proposal

Give `SubscriberBuilder` (and possibly also some related types) a `with_span_id(bool)` method for making the resulting subscriber include span IDs in its output as, say, `id=12345`.  If there are concerns about the `id` name conflicting with a possible `id` field on the span, one way to address this would be to add an `id_name: &str` argument to `with_span_id()` for letting the user set a custom name for the ID in the output.

### Alternatives

Currently, I'm trying to get `tracing-subscriber` to show span IDs the only way that seems to be supported: by defining a custom `FormatEvent` type, but even after copying a bunch of code from `tracing-subscriber`, it's just felt like banging my head against the wall, and I still don't have anything that compiles.

**Comment by davidbarsky** [comment]
The issue is that span IDs are not globally unique and the design of tracing-subscriber is optimized around including _all the span context you need_ in a single log event. If you want something globally unique, you can record a UUID as some at whatever level uniquely identifies a group of spans and log _that_. Adding an `with_span_id` method would likely be a footgun in other contexts, unfortunately.
