### ISSUE TITLE
Tracing lost after entering twice in the same span

### ISSUE THREAD

**Issue by zenria** [tokio-rs/tracing#358]
### Version

```
test-tracing v0.1.0 (/Users/philou/rust/test-tracing)
├── tracing v0.1.9
│   ├── tracing-attributes v0.1.3
│   └── tracing-core v0.1.6
└── tracing-subscriber v0.1.3
    ├── tracing-core v0.1.6 (*)
    └── tracing-log v0.1.0
        └── tracing-core v0.1.6 (*)
    └── tracing-log v0.1.0 (*)
```

`Cargo.toml` dependencies:
```
[dependencies]
tracing="0.1"
tracing-subscriber ="0.1.3"
```

### Platform

`Darwin siderant.home 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

### Description

Entering twice in the same span, then exiting from the second one, causes the span to be lost.

```rust
#[macro_use]
extern crate tracing;

use tracing::Span;
use tracing_subscriber::{EnvFilter, FmtSubscriber};

fn main() {
    tracing::subscriber::set_global_default(
        FmtSubscriber::builder()
            .with_env_filter(EnvFilter::new("[test]=debug"))
            .without_time()
            .finish(),
    )
    .unwrap();

    let span = debug_span!("test", c = 42);
    let _enter = span.enter();
    debug!("I'm in the test span");
    {
        let cloned = span.clone();
        let _enter2 = cloned.enter();
        debug!("In the 'nested' test span");
    }
    // suprisingly, the following sentence is printed in debug with no tracing...
    debug!("Not in test span anymore, but it should!");

    assert_eq!(span, Span::current())
}

```

The `assert_eq!` fails. The same happens if instead of cloning `span` I use `Span::current()`.

**Comment by hawkw** [comment]
Thanks for the report @zenria! 

This looks like a bug in `tracing-subscriber`, and I have a pretty good guess about what's causing it. It looks like there's an interaction between these two functions:
https://github.com/tokio-rs/tracing/blob/8c735e1dafeb40c10e524dc29fa39c321798cc44/tracing-subscriber/src/fmt/span.rs#L243-L252
and
https://github.com/tokio-rs/tracing/blob/8c735e1dafeb40c10e524dc29fa39c321798cc44/tracing-subscriber/src/fmt/span.rs#L254-L269

Note how the `push` function will only push the span to the stack if it isn't already on the stack. This was intended to avoid printing the same span twice when a span is entered inside of itself. The `pop` function then checks if the ID that was exited is at the top of the stack, and only removes it if it is. 

In cases where we enter a span _A_, enter a different span _B_, and enter the first span _A_ again, this code works correctly, since when we exit the nested span _A_, the top of the stack is span _B_, so we won't pop. When we exit span _B_ and then exit the outer span _A_, _A_ is now on the top of the stack, so it gets popped. In this case, we'd remain in span _A_ until the outermost enter is dropped. However, in the case where the same span is entered twice _in a row_ with no other span in between, exiting the second enter causes the span to be popped immediately. Since when we entered that span the second time, it was already on the top of the stack, we didn't push it a second time, but when we exit the more nested entry, it is on top of the stack, and it gets popped immediately.

I think we can change this by re-working the de-duplication logic here a bit. One solution would be to always push the span to the stack, but also track whether each ID on the stack is a duplicate. We could then use that information to do the de-duplication when _iterating_ over the current stack, rather than when pushing or popping.

Because you've included a minimal reproduction, this should be relatively simple to write a fix for. If you're interested, I'd be happy to provide some guidance. Alternatively, if you're not interested in working on it, I can fix it as soon as I have the chance to.

**Comment by zenria** [comment]
Thank you, for the analysis :)

I'll give a try fixing this !
