### ISSUE TITLE
Deadlock in tracing_log::TraceLogger

### ISSUE THREAD

**Issue by oblique** [tokio-rs/tracing#381]
### Crates

```toml
tracing = "0.1.9"
tracing-log =  "0.1.0"
log = "0.4.8"
simplelog = "0.7.4"
```

### Description

There is a dead lock in `tracing_log::TraceLogger`.

Almost all methods of `TraceLogger` lock at some point `self.spans` and then they call `TraceLogger::current_id`. However `current_id` relocks `spans` because it calls `clone_span`.

You can reproduce with:

```rust
use simplelog::{Config, LevelFilter, TermLogger, TerminalMode};
use tracing_log::TraceLogger;

fn main() {
    TermLogger::init(LevelFilter::Info, Config::default(), TerminalMode::Stdout).unwrap();

    tracing::subscriber::set_global_default(TraceLogger::new()).unwrap();

    let my_span = tracing::span!(tracing::Level::INFO, "my_span", answer = 42);
    let _enter = my_span.enter();

    log::info!("test1");
    tracing::info!("test2");
    log::info!("test3");
}
```

**Comment by hawkw** [comment]
Thanks for the report. This is a duplicate of #369, so if you don't mind, I'd like to close this issue so that we don't have two tickets tracking the same bug.

In the meantime, you may want to consider one of the following:
- Enable the "log" feature flag on the `tracing` crate. This will cause all the `tracing` macros and types to emit `log` records as well as traces, so you can consume them with a logger directly without having to use `TraceLogger` to convert them to `log` records.
- Use `tracing-subscriber::fmt` to format traces to the terminal, instead, and use `tracing-log`'s `LogTracer` to convert `log` records into traces, rather than converting traces into `log` records using `TraceLogger`. This will get you richer formatting for traces.

**Comment by oblique** [comment]
Sorry I didn't see #369 before reporting. I'm closing the issue.
