### ISSUE TITLE
Missing u8 implementation for trait tracing_core::field::Value

### ISSUE THREAD

**Issue by HermannLucas** [tokio-rs/tracing#389]
## Bug Report
The trait `tracing_core::field::Value` do not have an implementation for u8.
However it has an implementation for all the other integers types.

### Crates

tracing-core

### Description

Adding a field of type u8 to a tracing event gives the following error:

```
error[E0277]: the trait bound `u8: tracing_core::field::Value` is not satisfied
  --> example/src/main.rs:21:9
   |
21 |         error!(number = 0 as u8, "Invalid field");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tracing_core::field::Value` is not implemented for `u8`
   |
   = note: required for the cast to the object type `dyn tracing_core::field::Value`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by hawkw** [comment]
Thanks for the report! Looking at the code, I think this was an oversight or typo, since we generate implementations for every other integer type.

I think this should be a pretty easy fix — we'd just need to add `u8` to the macro invocation on this line:
https://github.com/tokio-rs/tracing/blob/97a8681fb9106ae57d17ba42ae177501f47fcd95/tracing-core/src/field.rs#L317
Note that for `i8`, there _is_ a generated `Value` implementation, two lines down: 
https://github.com/tokio-rs/tracing/blob/97a8681fb9106ae57d17ba42ae177501f47fcd95/tracing-core/src/field.rs#L319

We can change the line that generates impls for unsigned integers to match.

If you're interested in making this change, I'd be happy to merge a PR that adds it. Otherwise, I'm happy to do it as soon as I have a chance.

**Comment by hawkw** [comment]
@HermannLucas I'd like to get a `tracing-core` release out in the next few days, so if you're interested in making this change it would be great to get it in. Otherwise, I'd be happy to do it myself.

**Comment by HermannLucas** [comment]
Sorry for the delay.

I'm happy to make this change and submit a PR.

**Comment by hawkw** [comment]
Great, thanks!
