### ISSUE TITLE
subscriber: Move `FmtContext::visit_spans` to `layer::Context`; make it return an Iterator

### ISSUE THREAD

**Issue by davidbarsky** [tokio-rs/tracing#427]
(This is followup from https://github.com/tokio-rs/tracing/pull/420)

Several notes:
- The method [`FmtContext::visit_spans`](https://github.com/tokio-rs/tracing/blob/773c44054aed7f072ff03ee5dc64391f799dc02d/tracing-subscriber/src/fmt/fmt_layer.rs#L441) should be moved to [`layer::Context`](https://docs.rs/tracing-subscriber/0.1.6/tracing_subscriber/layer/struct.Context.html). 
- The new `layer::Context::visit_spans` should be renamed to something along the lines of `parents()`, and be made to return a newtype implementing `std::iter::Iterator`.
- The functions that relied on `FmtContext::visit_spans` should be refactored to rely on `layer::Context::parents`, taking care to preserve existing behavior (e.g., formatting the _current_ span the event originated in as per: https://github.com/tokio-rs/tracing/blob/773c44054aed7f072ff03ee5dc64391f799dc02d/tracing-subscriber/src/fmt/fmt_layer.rs#L463-L470)

**Comment by hawkw** [comment]
>   * The new `layer::Context::visit_spans` should be renamed to something along the lines of `parents()`, and be made to return a newtype implementing `std::iter::Iterator`.

There's already a `parents` method on `SpanRef`, which returns an iterator over the parents in order from the immediate parent to the root. I would call the new method something different — maybe `scope` or `current_scope`?

>   * The method [`FmtContext::visit_spans`](https://github.com/tokio-rs/tracing/blob/773c44054aed7f072ff03ee5dc64391f799dc02d/tracing-subscriber/src/fmt/fmt_layer.rs#L441) should be moved to [`layer::Context`](https://docs.rs/tracing-subscriber/0.1.6/tracing_subscriber/layer/struct.Context.html).
> 
>   * The functions that relied on `FmtContext::visit_spans` should be refactored to rely on `layer::Context::parents`

I don't think we should remove `FmtContext::visit_spans` or change its API, at least not yet. Since this interface was in the previous fmt API, I'd want to do a deprecation before removing it. Additionally, the more restricted interface of taking a closure and iterating internally would allow us more freedom to optimize if necessary (such as by going back to the recursive implementation we used to have, if benchmarking shows that it's better. Instead, I would just change `visit_spans` to internally use the new iterator.
