### ISSUE TITLE
Automatically instrumenting Err

### ISSUE THREAD

**Issue by nivekuil** [tokio-rs/tracing#545]
### Crates
tracing-attributes

### Motivation

When using `?` for error handling, trace events on returning an Err need to be handled in the caller explicitly. In a lot of cases I'd rather be lazy and instrument any returned Errs implicitly, in the same span that encompasses the function the Err was returned from.

### Proposal
I've been using this code which adds an `#[instrument_err]`:
https://gist.github.com/nivekuil/1c242e2627cc28e870699a28df5625d6 -- any interest in merging it?

### Alternatives
Explicitly handle the errors, but this is a lot of work if you don't necessarily care to that level of detail and you lose the actual function name the Err was returned from unless you explicitly create a Span.

**Comment by hawkw** [comment]
I'd be open to a PR to add this to `tracing-attributes`, especially if other folks think it would be useful (cc @tokio-rs/tracing). 

FWIW, we're also working on a very different way of integrating `tracing` and error-handling: a (not yet released) `tracing-error` crate is in the works that will provide the ability to record the current span context when an error is created, so that it can be displayed when the error is handled. That crate could also have the option to emit a new event when constructing an error.

**Comment by davidbarsky** [comment]
Personally, I'm in favor of something like this proposed feature landing. For layers like `metrics-tracing`, I can see some value in recording that an error occurred in a span's fields so that `tracing` users can record error/success counts. However, I think that might require deciding upon syntax for unrecorded/empty fields.

**Comment by hawkw** [comment]
>  However, I think that might require deciding upon syntax for unrecorded/empty fields.

I think recording the error as an event within the `instrument`-generated span is a much simpler solution than recording it as a new field on the span...

**Comment by davidbarsky** [comment]
@hawkw It absolutely is! I think I may have accidentally over-engineered the solution. It would also be semantically confusing.
