### ISSUE TITLE
Regression bug in tracing-subscriber 0.2.1?

### ISSUE THREAD

**Issue by roignpar** [tokio-rs/tracing#591]
### Version
```toml
tracing = "0.1.12"
tracing-subscriber = "0.2.1"
```
### Platform
```
Linux 5.4.18-1-MANJARO
```

### Crates
* `tracing-subscriber`

### Description
It seems that `EnvFilter` directive parsing behavior changed between `tracing-subscriber` `0.2.0` and `0.2.1`.
With the following code in `main.rs` of a crate named `hello`:
```rust
use std::env;

use tracing::{info, trace};
use tracing_subscriber::{filter::LevelFilter, EnvFilter, FmtSubscriber};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // by default, use info level
    let mut filter = EnvFilter::new(LevelFilter::INFO.to_string());

    // overwrite with env variable
    if let Ok(s) = env::var("RUST_LOG") {
        filter = filter.add_directive(s.parse()?);
    }

    FmtSubscriber::builder().with_env_filter(filter).init();

    info!("Hello info");
    trace!("Hello trace");

    Ok(())
}
```
I expect `RUST_LOG=hello=trace cargo run` and `RUST_LOG=trace cargo run` to have the same output:
```
Feb 20 13:45:19.085  INFO hello: Hello info
Feb 20 13:45:19.085 TRACE hello: Hello trace
```
Instead, `RUST_LOG=hello=trace cargo run` only outputs:
```
Feb 20 13:45:12.513  INFO hello: Hello info
```
With `tracing-subscriber 0.2.0` the output is as expected.

Is this part of making `EnvFilter` directive selection behave correctly or is it a regression?

**Comment by hawkw** [comment]
Yup, this isn't the expected behavior, looks like a regression. 

The change we made in 0.2.1 should have the effect that if you have a filter like `trace,hello=info`, `TRACE`-level events in `hello` should _not_ be enabled. The behavior when the more specific filter (in this case, the filter for `hello`) is _more_ verbose shouldn't be changed.

My guess is that the issue is related to this function:
https://github.com/tokio-rs/tracing/blob/d2489fd84fa345258639adf36a3e65fb2058dd19/tracing-subscriber/src/filter/env/directive.rs#L412-L421
