### ISSUE TITLE
Don't forward empty span messages to log

### ISSUE THREAD

**Issue by sagebind** [tokio-rs/tracing#607]
I am currently experimenting with migrating my library [Isahc](https://crates.io/crates/isahc) from the `log` crate to `tracing` in order to get better per-request tracing, but the migration is not as seamless as I was hoping for (though I mostly like what I see). One large problem is how the `log` feature on the `tracing` crate handles entering and exiting spans; as alibrary author, I want to maintain the ability to output quality logs via the `log` abstraction for users using that crate, while also delivering additional value for users of `tracing`.

Unfortunately, migrating to `tracing` reduces the "quality" of logs emitted through the `log` abstraction because it is filled with a lot of mostly empty messages indicating when spans are entered, exited, and closed:

```
[2020-02-27T04:56:48Z INFO  isahc::agent] <- dispatch
[2020-02-27T04:56:48Z INFO  isahc::agent] -- dispatch
[2020-02-27T04:56:48Z INFO  isahc::agent] poll_messages; 
[2020-02-27T04:56:48Z INFO  isahc::agent] -> poll_messages
[2020-02-27T04:56:48Z INFO  isahc::agent] <- poll_messages
[2020-02-27T04:56:48Z INFO  isahc::agent] -- poll_messages
[2020-02-27T04:56:48Z INFO  isahc::agent] dispatch; 
[2020-02-27T04:56:48Z INFO  isahc::agent] -> dispatch
[2020-02-27T04:56:48Z INFO  isahc::agent] <- dispatch
[2020-02-27T04:56:48Z INFO  isahc::agent] -- dispatch
[2020-02-27T04:56:48Z INFO  isahc::agent] poll_messages; 
[2020-02-27T04:56:48Z INFO  isahc::agent] -> poll_messages
[2020-02-27T04:56:48Z INFO  isahc::agent] <- poll_messages
[2020-02-27T04:56:48Z INFO  isahc::agent] -- poll_messages
[2020-02-27T04:56:48Z INFO  isahc::agent] dispatch; 
[2020-02-27T04:56:48Z INFO  isahc::agent] -> dispatch
```

(Here the logger implementation is `env_logger`, but a user could use any implementation. Also keep in mind that this just from an experimental branch.)

In the context of a tracing subscriber, this structured information is of course quite valuable and can be presented in very useful ways. But in the context of a `log` logger, these logs seem pretty spammy and useless; since the fields of the span are not included on enter/exit, the only value that _might_ come from this is the timestamps, but even that seems like a stretch to me.

My gut reaction to this behavior was that maybe all of my non-public methods should be using `Trace`-level spans so that users wouldn't get this spam unless they set their log level to `trace`. I often recommend to users to send me snippets of their `trace` logs whenever they think they are encountering a bug, but even then these log lines seem like they still would be just noise and not helpful.

I do see that the `#[instrument]` attribute optionally takes a `level`, but if spans should be `trace` everywhere except public methods, why is `info` the default level?

A similar problem is the logs when spans are created. Emitting a log when a span is created can be quite useful, except when it has no fields; in that case maybe spans with no fields should not be logged.

Ultimately I'm looking to benefit from tracing's more structured approach for both me when debugging concurrent behaviors and for users making use of tracing in their apps, but without giving existing `log` users the short shrift. I might be using `tracing` wrong or have the wrong expectations here and I just need to do some more learning first. Maybe there's a good reason for this behavior that I'm not grasping?

**Comment by hawkw** [comment]
> Unfortunately, migrating to `tracing` reduces the "quality" of logs emitted through the `log` abstraction because it is filled with a lot of mostly empty messages indicating when spans are entered, exited, and closed:

The problem is that it's really hard to present the contextual data that spans represent to `log` in a way that works well. Since the `log` feature supports using `tracing` without a `Subscriber` to actually track span contexts, we can't really annotate the log records we emit for events with span data at all. Thus, I thought the enter/exit logs would be useful since they provide _some_ context.

If that's not the case, I'm certainly open to revisiting or removing them, although we should probably make sure that there aren't other users of the `log` feature who do find these useful. 

Ideally, I think we would want to have a better way of tracking span contexts & presenting that information to `log` users. However, I'd also like to avoid making that system too complex — it runs the risk of essentially reimplementing everything a `tracing` subscriber does. If you have any suggestions, I'd be happy to hear them!

> Emitting a log when a span is created can be quite useful, except when it has no fields; in that case maybe spans with no fields should not be logged.

I'm definitely open to changing that so that span creation is only logged when there are fields, especially if we remove some of the other span-related logs!

**Comment by sagebind** [comment]
> The problem is that it's really hard to present the contextual data that spans represent to `log` in a way that works well.

I can see where you're coming from and that makes some sense, but I'd argue that if a user wants that contextual data, they should switch their output to a `Subscriber` instead of trying to pass it somehow to a `log` logger.

**Comment by hawkw** [comment]
> if a user wants that contextual data, they should switch their output to a `Subscriber` instead of trying to pass it somehow to a `log` logger.

Sure, this is probably true...at the time, when I was writing the `log` integration, it seemed like a shame to not emit this information when we _could_ do so.

> Mainly because that data simply didn't exist when the library was using just `log` before, so it wasn't a problem.

This is true in the case of a library that previously used `log` adding `tracing` instrumentation (e.g., the situation you're in with `isahc`). But, in the case of a library which used `tracing` from day one, there could potentially be a lot of vital information in spans which would otherwise not be recorded at all. 

---

Here's a thought: what if the span enter/exit/close `log` records had a different `log` target; maybe "tracing::span_events" or something? That way, they could be filtered out separately from the `log` records emitted by event, but you could enable that target to opt in. The span creation log records should probably have the default target for the module path they occurred in, at least when the span has fields, since users are more likely to want to see that information. 

What do you think?

**Comment by sagebind** [comment]
Interesting idea, I like the sound of that, it would work well for my own use-case at least.

**Comment by hawkw** [comment]
Okay, I'll see if anyone else using the log integration has an opinion, and then we can make that change pretty easily. As a side note, @sagebind, thanks for the thoughtful discussion on this! I appreciate it!

**Comment by davidbarsky** [comment]
> Here's a thought: what if the span enter/exit/close log records had a different log target; maybe "tracing::span_events" or something? That way, they could be filtered out separately from the log records emitted by event, but you could enable that target to opt in. The span creation log records should probably have the default target for the module path they occurred in, at least when the span has fields, since users are more likely to want to see that information.

The more I think about it, the more I like this approach. It can also be a way of tackling/validating two independent issues—this proposed behavioral change _and_ moving Hyper/h2 to `tracing`. By moving span-related events/data to a dedicated target, `log` users who are using `tracing`-instrumented libraries don't need to aware of `tracing`-specific data _unless_ they opt into a specific target. Similarly, `tracing` users aren't aware that anything changed.

---

I think this also has the nice side effect of (maybe!) driving more attention to the customizability of targets in `tracing` and `log`, which is a highly underrated feature.

**Comment by najamelan** [comment]
I second that. log backends like flexilogger let you set different log levels per target. Also it can even just be grepped out.
