### ISSUE TITLE
Expose tracing::level_enabled

### ISSUE THREAD

**Issue by Kobzol** [tokio-rs/tracing#620]
## Feature Request
Make the `tracing::level_enabled` function public.

### Crates
tracing

### Motivation
Sometimes I want to trace data that is expensive to prepare/format. When tracing is disabled, I have to pay for preparing the data, only for it to be thrown out, because the `tracing::event!` call will fail on checking the enabled level.

If this function was public, I could do:
```rust
if tracing::level_enabled(tracing::Level::INFO) {
    let data = // expensive process
    tracing::info!(data, ...);
}
```

**Comment by hawkw** [comment]
Hmm. This macro isn't currently public because it's an internal implementation detail that probably _doesn't_ actually do what you want to be able to do.

In particular, it doesn't provide a complete picture of whether or not a particular span or event will be enabled or disabled. It _only_ indicates whether a level has been globally disabled at compile-time using the [`max_level_*`/`release_max_level_*` Cargo features](https://docs.rs/tracing/0.1.13/tracing/level_filters/index.html#compile-time-filters). 

That means that, for example, if you are using `tracing-subscriber`'s [`EnvFilter`](https://docs.rs/tracing-subscriber/0.2.2/tracing_subscriber/filter/struct.EnvFilter.html), and you set the environment variable `RUST_LOG=warn`, in the code example you posted above, `level_enabled!` would evaluate to `true`, even though the `INFO` level won't be enabled by the subscriber. This means that `data` would still be evaluated.

There are, however, other ways to avoid evaluating an expensive expression unless you are actually going to record a piece of data. If you declare fields using the `name = value` form, the `value` expression will only be evaluated if the subscriber indicates that a particular span or event is enabled. Therefore, you could just do this:
```rust
tracing::info!(data = /* expensive process */, ...);
```

Similarly, if the expensive expression is particularly long and you don't want to write it inside the `info!` macro, you could do something like this
```rust
let data = || {
    /* expensive process */
};
tracing::info!(data = data(), ...);
```
in that case, the `data` closure will only be called if the event is enabled.

**Comment by hawkw** [comment]
> Similarly, if the expensive expression is particularly long and you don't want to write it inside the `info!` macro, you could do something like this
> 
> ```rust
> let data = || {
>     /* expensive process */
> };
> tracing::info!(data = data(), ...);
> ```
> 
> in that case, the `data` closure will only be called if the event is enabled.

Something we could do to make this usage a little more ergonomic, actually, is to add a [`Value`](https://docs.rs/tracing/0.1.13/tracing/trait.Value.html) impl for `F: Fn() -> T, where T: Value`. Then, you could just say:

```rust
let data = || {
    /* expensive process */
};
tracing::info!(data, ...);
```

I'm not totally sure if there aren't any other issues with doing this, but it's an idea...

**Comment by Kobzol** [comment]
I went through the source code of the `event!` macro again and now I realize that the filtering is actually more complex. Now that you mentioned it, the solution is obvious in retrospect - I didn't realize that the macro arguments will not actually be evaluated if the trace is filtered. And the solution with the closure is pretty elegant.

I don't think that adding an impl for functions returning a `Value` is necessary, your solution works fine. This issue can serve as a future guide for others who might think about potential formatting efficiency :-) You can close it. Thanks!

**Comment by hawkw** [comment]
Great, glad I could answer your question. Do you think this could be better documented? If there are any potential documentation changes that would've made this clearer, I'd be happy to make them.

**Comment by Kobzol** [comment]
It's probably a niche usecase, but it would be nice if it was mentioned as an example in the docs.
