### ISSUE TITLE
fmt::Subscribers don't want their output to be captured

### ISSUE THREAD

**Issue by acfoltzer** [tokio-rs/tracing#638]
### Version

```
"checksum tracing 0.1.13 (registry+https://github.com/rust-lang/crates.io-index)" = "1721cc8cf7d770cc4257872507180f35a4797272f5962f24c806af9e7faf52ab"
"checksum tracing-attributes 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)" = "7fbad39da2f9af1cae3016339ad7f2c7a9e870f12e8fd04c4fd7ef35b30c0d2b"
"checksum tracing-core 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)" = "0aa83a9a47081cd522c09c81b31aec2c9273424976f922ad61c053b58350b715"
"checksum tracing-log 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = "5e0f8c7178e13481ff6765bd169b33e8d554c5d2bbede5e32c356194be02b9b9"
"checksum tracing-serde 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = "b6ccba2f8f16e0ed268fc765d9b7ff22e965e7185d32f8f1ec8294fe17d86e79"
"checksum tracing-subscriber 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)" = "dedebcf5813b02261d6bab3a12c6a8ae702580c0405a2e8ec16c3713caf14c20"
```

### Platform

Linux localhost 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Crates

`tracing-subscriber`

### Description

I cannot get the output of a `fmt::Subscriber` to coöperate with settings that want to capture or redirect stdio. For example, the tracing messages all show through the test runner output of `cargo test`, even when the `--nocapture` flag is not set.

I have tried to even make my own `MakeWriter` that calls `eprintln!()` directly, but that only seems to hide some of the output. It would be nice to have an easy way to clean up test output short of disabling the output entirely, since it's nice to have the output there in case a test fails.

**Comment by hawkw** [comment]
My first thought is that we should be able to provide an API like [`env_logger`'s `Builder::is_test`](https://docs.rs/env_logger/0.7.1/env_logger/struct.Builder.html#method.is_test). This changes the `env_logger` to emit logs with `eprint!`/`print!` rather than `write!(stdout, ...)`:
https://github.com/sebasmagri/env_logger/blob/68a170094649c48c6ce7471acf3a33fd2799541c/src/fmt/writer/termcolor/extern_impl.rs#L104-L115

However, it seems like you've tried that and it wasn't sufficient:
> I have tried to even make my own `MakeWriter` that calls `eprintln!()` directly, but that only seems to hide some of the output.

Does your test spawn multiple threads? My understanding is that `cargo test` only captures output from the main test thread. If any other tests invoke `println!`, their output will not be captured. I think you'd see the same behavior with `env_logger`'s test mode.

If that's an issue, we could probably come up with a more complex solution to ensure logs from all threads are always captured. Perhaps we could have a test mode that buffers all log lines rather than printing them, and has a drop guard in the test function that prints all those lines when dropped, ensuring that they're all printed on the main thread. This would ensure that all log lines from all threads are definitely always captured. It might have some performance impact, though, and means that all `tracing` logs would be printed after anything printed by `println!`/`dbg!`/etc elsewhere in the codebase.

What do you think? @LucioFranco and @yaahc, I know you've both had some opinions on how the `fmt` subscriber/layer should interact with tests, so I'd love to hear your thoughts as well.

@acfoltzer, if you're interested in working on this, I'd be happy to provide guidance once we decide what the right design is. No pressure, though! If you don't have the time, someone else will be able to.

**Comment by hawkw** [comment]
Somewhat related: #201

**Comment by yaahc** [comment]
does tracing have support for a dedicated logging thread? Wondering if we could make the main thread the logging thread and redirect all logs to be immediately printed in main when running tests.

If that's not possible then the drop guard sounds okay, though I don't love the log reordering issue that would introduce, also if setting up the drop guard needs to be done manually that sounds like an unpleasant API and I think would be a strong motivation for adding #201 to handle the drop guard for you.

**Comment by yaahc** [comment]
Another part of me feels like this is more a problem with the way rust runs tests. The fact that it only captures println / eprintln and not write!(stdout) sounds bad, and the fact that it only does it on the main thread sounds even worse. I'm wondering if the correct solution here would be to just look into how rust handles tests and possibly fix the issue upstream.

**Comment by LucioFranco** [comment]
I personally, want fmt to log out to a file so I can upload it somewhere like s3 and look at it later while still keeping regular output from tests.

**Comment by hawkw** [comment]
> does tracing have support for a dedicated logging thread? Wondering if we could make the main thread the logging thread and redirect all logs to be immediately printed in main when running tests.

Not yet. adding something like this is in the queue of things to do — I've started on it.

> I personally, want fmt to log out to a file so I can upload it somewhere like s3 and look at it later while still keeping regular output from tests.

You can do that now with the `MakeWriter` interface.
