### ISSUE TITLE
ci: cargo hack not always present in the cache

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#648]
### Description

Sometimes, the CI builds that run `cargo hack check` fail with
```
Run cargo hack check --feature-powerset --no-dev-deps
error: no such subcommand: `hack`

	Did you mean `check`?
##[error]Process completed with exit code 101.
```

This seems to imply that the `cargo hack` binary that we cached wasn't there?

It _appears_ that this will sometimes happen for a particular branch, rather than for all branches. Once this starts happening for a branch, it remains in this state even when builds are restarted, but sometimes gets back into a good state after a few days.

**Comment by hawkw** [comment]
I'm going to try to fix this by checking if the cached version is present, and forcibly installing `cargo hack` if it isn't. This seems like a brute-force solution, but I'd like to be able to merge PRs again, and I don't really understand the caching stuff.

It's possible that @darinmorrison, who added the caching to our CI build, may have more insight into the right way to fix this. I'd welcome any input.

**Comment by hawkw** [comment]
#649 fixes this, but not in the nicest way.

**Comment by hawkw** [comment]
Apparently there is also https://github.com/actions-rs/install which implements similar cargo subcommand caching. Possibly we could just be using that?

**Comment by darinmorrison** [comment]
@hawkw I'll take a look and see if I can figure out what's going on. As long as the jobs are triggered in the right order, according to `needs`, and the install job didn't fail, I don't see how it end up in this state. It's possible there's something weird going on with github actions itself though. I've encountered some strange bugs in the past that just seem to disappear.

However, the `actions-rs` install action is probably a better solution in the long run. This didn't exist back when I started using caching for cargo installs. I'd be willing to port the work over to that after I spend some time learning how it works.

**Comment by darinmorrison** [comment]
I'm looking at [this run](https://github.com/tokio-rs/tracing/actions/runs/531116855).

It appears that `cache-cargo-hack` job succeeded, with a cache hit for the key:

```
Cache cargo-hack/bin

    Cache Size: ~1 MB (998810 B)
    /bin/tar -xz -f /home/runner/work/_temp/b192946f-341b-4dd6-be5d-93880fe4901c/cache.tgz -C /opt/hostedtoolcache/cargo-hack/bin
    Cache restored from key: cargo-hack-bin-fa8395a0615755a7620423cb720ae06bc94ffbf3a082038dcb48589622911bb5
```

However, when looking at the `cargo-hack` sub jobs, something strange is happening.

The `cargo-hack (tracing-attributes)` job successfully restores the cache:

```
Run actions/cache@v1

    Cache Size: ~1 MB (998810 B)
    /bin/tar -xz -f /home/runner/work/_temp/b44b989f-cfdf-48c6-b982-51d5a1c0d72d/cache.tgz -C /opt/hostedtoolcache/cargo-hack/bin
    Cache restored from key: cargo-hack-bin-fa8395a0615755a7620423cb720ae06bc94ffbf3a082038dcb48589622911bb5
```

But the adjacent `cargo-hack (tracing-core)` job fails to the restore the cache:

```
Run cargo-hack/bin

    Cache not found for input keys: cargo-hack-bin-4eeddaf1127317a664721f5986e83ac73ee1840136c84a76a523c66c51d1c234.
```

Notice that the key for the failing job is incorrect:

```cargo-hack-bin-4eeddaf1127317a664721f5986e83ac73ee1840136c84a76a523c66c51d1c234```

is wrong, it should be:

```cargo-hack-bin-fa8395a0615755a7620423cb720ae06bc94ffbf3a082038dcb48589622911bb5```

Based on this, I have a theory about what is causing the problem.

Each `cargo-hack` sub job has to make a query to the github api (via `curl` and `jq`) to fetch the current version of `cargo-hack`, which is used to compute the cache key (and if the key lookup misses, to rebuild the binary).

Since one of the sub jobs succeeded but another did not, I suspect the CI job may be encountering API rate limiting (responding with null data), which is causing some branches to use invalid key data. This will cause the cache restore to fail, and the binary won't be present in the path.

One way to verify that this is what's happening is to print the response to the `curl` request.

If the issue is rate limiting, it might be enough to set up a secret for authentication (like [this](https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications)), which can then be used in the CI job.

**Comment by hawkw** [comment]
Ah, that's interesting! Thanks for looking into this.

**Comment by darinmorrison** [comment]
No problem 🙂

When I get a chance I'll try to submit a PR that prints the response from the API query and also implements authenticated queries.

But the fix you implemented seems fine and is probably a good idea to have there just in case the API is non-responsive for some other reason.

**Comment by hawkw** [comment]
Sounds good to me. Since we have a workaround, it's not a huge deal to get this fixed right away. Let me know if there's anything you need me to use my admin privileges for?

**Comment by darinmorrison** [comment]
Sorry I never got back to this. I was hoping I'd be able to come back and fix this but I'm not sure I'll be able to do that now.

But as a final note, you might be able to re-use the script for computing the key for the `cargo-audit` job [here](https://github.com/tokio-rs/tracing/blob/280b664034fe18fc38accb96d6c4391bac81dc20/.github/workflows/CI.yml#L238-L240) as a way to avoid the rate limiting from the GitHub API (assuming crates.io doesn't do rate limiting also).

Anyway, I'm so sorry for the problems I've caused here. Thanks for working with me and giving me feedback on those CI changes originally and for letting me contribute. I wish I would have been more careful with my contributions to make sure there were no unintended consequences...

Before I go, I just want to thank you and the other maintainers for all of your hard work and for running a great project.

**Comment by hawkw** [comment]
Please don't worry about it! All the work you put into this was greatly appreciated and we would love to see you come back! :)

**Comment by taiki-e** [comment]
FYI: we are distributing compiled binary files of `cargo-hack` via GitHub release. Installing it is faster than using a cache (<1 second). See https://github.com/taiki-e/cargo-hack/pull/89#issuecomment-723754842 for (cross-platform) installing on CI.
