### ISSUE TITLE
Remove json support from tracing-subscriber's default features

### ISSUE THREAD

**Issue by Ralith** [tokio-rs/tracing#653]
json is unnecessary for many purposes, and the dependencies it pulls in can substantially fatten the build of an application which does not otherwise require serde or json support. It'd be nice to be able to use tracing-subscriber without having to copy-paste `default-features = false, features = ["env-filter", "fmt", "ansi", "chrono"]` for pretty, comparatively lightweight terminal output around all the time.

**Comment by hawkw** [comment]
Yeah, the JSON feature should probably not be on by default. We can change this, but it'll have to wait for `tracing-subscriber` 0.3.

I think in general, we may want to prune the `tracing-subscriber` crate's default features a bit in 0.3, since opting out of features is significantly more fraught than opting into them.

**Comment by bnjjj** [comment]
As I already introduce breaking changes in my PR #662 I can add this one also inside if you want ?

**Comment by hawkw** [comment]
@bnjjj A PR to make this change would be great, and would definitely help us move towards getting 0.3 ready to release. Let's do it in a separate pull request from #662, though. Since we merge pull requests by squashing them into a single commit, it's best for each one to contain one logical change.
