### ISSUE TITLE
Render variables consistently with Rust's macros

### ISSUE THREAD

**Issue by kellytk** [tokio-rs/tracing#654]
### Version

tracing = "0.1.13"
tracing-subscriber = "0.2.3"

### Platform

Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64

### Description

When a variable is traced, the output includes the variable:

```
let bar = "bar";

info!(bar);

// INFO demo::foo: bar="bar"

info!("{}", bar);

// INFO demo::foo: bar
```

However `panic!` renders only the value of the variable:

```
panic!(bar);

// thread 'tokio-runtime-worker' panicked at 'bar', packages/demo/src/foo/mod.rs
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by hawkw** [comment]
Tracing models all recorded data as key-value pairs, called [fields](https://docs.rs/tracing/0.1.13/tracing/field/index.html). How (and if) these fields are formatted is a presentation concern that's left entirely up to the `Subscriber` implementation in use.

Since you're using the `FmtSubscriber` in `tracing-subscriber`, you can actually customize how fields are displayed. The default formatter formats the whole key-value pair, because ignoring the field name is throwing out information that's valuable for some users. But, if you want to see different behavior, you can use the [`fmt_fields` method](https://docs.rs/tracing-subscriber/0.2.3/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.fmt_fields) on the subscriber builder to override how fields are formatted, like so:
```rust
    use tracing_subscriber::fmt::{self, format};

    fmt::Subscriber::builder()
        .fmt_fields(format::debug_fn(|writer, _, value| {
            write!(writer, "{:?}", value)
        }))
        .init();
```
Then, your demo output will look like this:
```
Mar 31 14:27:44.863  INFO demo::foo: "bar"
Mar 31 14:27:44.863  INFO demo::foo: bar
```

(FWIW, if the goal is specifically to get formatting consistent with the Rust standard library, it's worth noting that, although panics only render the `fmt::Display` output of the arguments to the panic, the `dbg!` macro formats both the result of an expression _and_ the string representation of the expression, which could be a variable name...so, in your example, [`dbg!` will output `bar = "bar"`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ec9920a3eec4c513ff375ff3a02dcd9d))

**Comment by kellytk** [comment]
Thank you very much for your detailed and helpful reply.

**Comment by hawkw** [comment]
@kellytk Glad I was able to help! If you have any more questions, please feel free to ask away, either here or on [Discord](https://discord.gg/tokio)

**Comment by kellytk** [comment]
@hawkw Is it possible for the surrounding " to be omitted?  My goal is not to output `INFO demo::foo: bar="bar"` or `INFO demo::foo: "bar"`, but `INFO demo::foo: bar`.

**Comment by hawkw** [comment]
@kellytk `&str` is one of tracing's primitive value types. The default field formatter will format it using its `fmt::Debug` implementation, which includes quotes {this is also 9how `std::dbg!` formats `&str` values](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=22787e8a48cae59690b808ca44be440d)).

If you would prefer to format it with `fmt::Display`, which will not include quotes and won't escape special characters, you can prefix the field value with `%`, which will record it as a `Display` value instead:
```rust
tracing::debug!(foo = %"foo");

let bar = "bar";
tracing::debug!(%bar);
```

Alternatively, you could provide your own [field formatter](https://docs.rs/tracing-subscriber/0.2.4/tracing_subscriber/fmt/format/trait.FormatFields.html) implementation that formats strings using their `fmt::Display` implementation. Unfortunately, you can't do this using `format::debug_fn` as in the example I posted above, since `debug_fn` takes a single closure and receives all values as `fmt::Debug`. Instead, you would have to implement the [`MakeVisitor` trait](https://docs.rs/tracing-subscriber/0.2.4/tracing_subscriber/field/trait.MakeVisitor.html) and return a [field visitor](https://docs.rs/tracing-core/0.1.10/tracing_core/field/trait.Visit.html) that implements the `record_str` method as well as `record_debug`, and records the string passed into that method using `fmt::Display`. The documentation has an [example](https://docs.rs/tracing-core/0.1.10/tracing_core/field/trait.Visit.html#examples) showing how additional `Visit` trait methods can be implemented to provide more specialized ways to record values of various types.

**Comment by kellytk** [comment]
@hawkw Thank you once again for your detailed and helpful reply.  As having this feature available would be helpful to other users of `tracing`, would you accept a PR adding the `Display` field formatter?  If not, do you foresee any reason why I would not be able to implement it as a standalone crate?

**Comment by hawkw** [comment]
A PR adding a formatter that formats everything with `Display` would be great. Note that the `record_debug` method would still have to exist, and it would have to record values using their debug implementations, because values recorded as `Debug` trait objects (e.g. `tracing::info!(?my_struct_implementing_debug)`) aren't guarnateed to _have_ display implementations. However, it would be able to record all _primitive_ value types with `Display`.

**Comment by kellytk** [comment]
@hawkw I've forked `tracing` and created a [new branch](https://github.com/kellytk/tracing/tree/display-field-formatter).  Should the feature be added to `tracing-subscriber/src/fmt/format/display.rs` or do you have another preference?

**Comment by hawkw** [comment]
Seems like the right place to me.

**Comment by kellytk** [comment]
@hawkw I've set up a local environment, cloned the fork, and created the file.  I'm also reading through the links you provided.

In setting up a local environment I changed the program's dependencies from:

````
tracing = "0.1.13"
tracing-subscriber = "0.2.3"
````
to:

````
tracing = { path="path/to/tracing/tracing" }
tracing-subscriber = { path="path/to/tracing/tracing-subscriber" }
````
Although `cargo build` runs as expected, and progress is not blocked, my IDE (VS Codium+RLS) reports an error that the `tracing` crate cannot be found.  I use path-based dependencies successfully regularly therefore I suspect the issue is due to `tracing` using workspaces.  Do you know of a solution?  I would have thought `path/to/tracing` would be a sufficient path for both dependencies as their package names match their workspace member names.

I'd like to ensure that I'm thinking properly about how the feature will be used.  Is the following change to user code correct or how should it differ?
````
let subscriber = FmtSubscriber::builder()
    .fmt_fields(format::display::display_fn(|writer, _, value| {
        write!(writer, "{}", value)
    }))
    /*.fmt_fields(format::debug_fn(|writer, _, value| {
        write!(writer, "{:?}", value)
    }))*/
    .finish();
````
