### ISSUE TITLE
instrument macro: format fields with `Display` instead of `Debug`

### ISSUE THREAD

**Issue by thomaseizinger** [tokio-rs/tracing#661]
## Feature Request

The instrument macro should format fields with `Display` instead of `Debug`.

### Motivation

The instrument macro is a really nice way of instrumenting the code without the clutter of creating spans and assigning fields.
Unfortunately, the macro uses the `Debug` trait to format fields which makes the logs unnecessary verbose.

### Proposal

I propose to switch from `Debug` to `Display`.

I would argue that (at least as of now), annotating functions with instrument is the easiest way to get clean and still useful logs. By carefully choosing the fn name, fn argument names and select, which arguments should be printed it is relatively easy to get amazing logs without too much manual work.

The only downside of this approach is that the arguments are formatted with `Debug` instead of `Display` :(

### Alternatives

Make the macro configurable to support both `Display` and `Debug`.

**Comment by hawkw** [comment]
> ###
> 
> Make the macro configurable to support both `Display` and `Debug`.

I'd prefer to make this configurable than to change `#[instrument]` to use `Display`. The main reason it uses `Debug` currently is that _significantly_ more types implement `Debug` than `Display`, so changing it to `Display` now would break a lot of code. I'm sure there are a lot of existing uses of `#[instrument]` where one or more arguments to an instrumented function doesn't implement `Display`.

We _could_ just add an option to opt in to formatting all fields using `Display` rather than `Debug`. That would be fairly easy to add. However, personally, I think it might be better to implement this as part of the proposal for #650, where we would allow passing expressions to be evaluated as fields in the `fields(...)` argument to `#[instrument]`. Then, we could just use the existing macro syntax here as well.

For example, if you had a function like
```rust
fn my_great_function(display_arg: &dyn fmt::Display, debug_arg: &dyn fmt::Debug) {
    // ...
}
```
you could write
```rust
#[instrument(fields(%display_arg, ?debug_arg)]
fn my_great_function(display_arg: &dyn fmt::Display, debug_arg: &dyn fmt::Debug) {
    // ...
}
```
or just
```rust
#[instrument(fields(%display_arg)]
fn my_great_function(display_arg: &dyn fmt::Display, debug_arg: &dyn fmt::Debug) {
    // ...
}
```
(assuming we don't change fields to be opt-in, which would be a breaking change, so it wouldn't happen any time soon)

**Comment by thomaseizinger** [comment]
> The main reason it uses Debug currently is that significantly more types implement Debug than Display, so changing it to Display now would break a lot of code.

That is certainly true, however, the `Debug` impl is supposed to be derived and clutters logs extremely. These days I usually try to use the Display impl of my types in log statements, makes them much more predictable and easier to read. To expand on what I mean by predicatable: `Debug` impls always contain the name of the type. Hence, while writing a log statement, it is a common mistake to repeat the name of what you are logging, which results in the name being printed twice:

```rust
tracing::info!("connection established to peer {:?}", peer_id)
```

Will print:

```
[INFO] connection established to peer PeerId(Qma9T5YraSnpRDZqRR4krcSJabThc8nwZuJV3LercPHufi)
```

What I would actually want to be printed is (which I can achieve by using the Display-impl):

```
[INFO] connection established to peer Qma9T5YraSnpRDZqRR4krcSJabThc8nwZuJV3LercPHufi
```

That being said, I am not arguing against the configurability aspect. We shouldn't lock users out of using the `Debug` impl if they want to. However, I would be very much in favor of changing the default behaviour to use `Display`. If this breaking change is accommodated by a migration strategy (for example, having to prepend a `?` to the name in the fields expression) then the upgrade path shouldn't be too painful.

That said, I don't have an opinion on whether or not this is implemented as part of https://github.com/tokio-rs/tracing/issues/650 or not :)
The essence of my feature request is:

**I want to have beautiful logs with as little (maintenance) work as possible!**

Ideally, the only thing I want to do is:

1. Add the `instrument` attribute
2. Choose a level
3. Potentially exclude some fields although with https://github.com/tokio-rs/tracing/issues/651, the need for this is massively reduced

I think tracing is already massively superior to `log` when it comes to beautiful logs because it allows us to keep log messages short and not repeat context all over the place in every message.
Being able to define spans that render to beautiful logs almost for free by annotating functions with `instrument` would make this even better :)
At the moment, I have to manually create my spans, adding noise to the code and making it harder to maintain by duplicating the names of parameters.

**Comment by hawkw** [comment]
I'm glad you think that `tracing` diagnostics are beautiful, that's great to hear!

And, I definitely want to support this use-case and make it easier to format fields with `Display` when using `instrument`. We could also add an argument to `instrument` that causes it to automatically format all fields with `display`, without having to write them out explicitly as in #650. That could reduce maintenance burden a bit in cases where all arguments to a function have `Display` implementations. Or, we could even add a separate `#[instrument_display]` attribute that uses `Display` by default.

However, I'm not sure if it makes sense to change the default for a few reasons:

1. I think the default behavior should work "out of the box" for a majority of users. I don't think most people are implementing `Display` for _all types_ that might be passed as an argument to a function annotated with `#[instrument]` (though if a large number of people stated otherwise, I'd reevaluate!). 
2. Furthermore, a number of standard library types (e.g. `Vec`, `HashMap`, `HashSet`, slices, tuples, etc) don't implement `Display`, but have "pretty" `Debug` implementations. For example, rather than printing the actual internal structure of a `HashMap`, it's `Debug` impl formats it like `{"key1": "value1", "key2": "value2"}`. Since users can't _add_ `Display` implementations to these types, this means that adding `#[instrument]` to any function that takes a `HashMap` (or `HashSet`, `Vec`, slice, tuple, and so on) as an argument would result in a compiler error out of the box, even if all the user-defined types in the program _do_ have `Display` implementations.
3. The reason I'd prefer to avoid a breaking change here is less about the lack of a migration path (which we can easily provide), and more about not having to _wait_ for the next breaking change release before we can provide support for this use-case. Because `tracing-attributes` is re-exported by `tracing`, breaking changes to `#[instrument]` are breaking changes to the `tracing` crate. Since we want to keep `tracing` fairly stable, we'll hold off on making any breaking changes until we have a large number that need to be made. Therefore, if we start with the breaking change, users who want to use `Display` might be waiting a fairly long time. I'd prefer to make an additive change _now_ that lets you start using `Display` formatting with `#[instrument]` sooner. When we're preparing a breaking change release, I'm always open to revisiting the defaults.

Hopefully that makes sense?

**Comment by yaahc** [comment]
I would have to change a LOT of code if we changed the default to display, I don't think it would be a simple migration.

That said, I'm in favor of the second name for the macro, that way if someone wants to use display as the default they can just do `use tracing::instrument_display as instrument;` and get the exact behavior you desire. That plus #650 is the right approach imo. Which will make an arg to change the default to display in the current macro unnecessary.

**Comment by thomaseizinger** [comment]
The 2nd macro approach is a really good idea! That works for me :)

**Comment by SirWindfield** [comment]
Isn't there already an operator for this: `%`?

**Comment by hawkw** [comment]
@SirWindfield yes, and now that #672 has been published, it's possible to use `%` in `#[instrument]`.

**Comment by thomaseizinger** [comment]
> Isn't there already an operator for this: `%`?

Yes but prior to #672, using that required to manually create spans which is quite verbose and meant you effectively had to choose between nice logs and verbose code or verbose logs and nice code.

That is no longer the case, so I am tempted to close this issue. Especially given that it is unlikely for the default to change anytime soon.

Thanks everyone!

**Comment by hawkw** [comment]
@thomaseizinger also, the plan currently is that in `tracing`/`tracing-attributes` 0.2, adding parameters as fields will be opt-in rather than opt-out, so it should be pretty natural to use the `%` sigil in `instrument` exactly the same as how you would in the `event!` and `span!` macros.
