### ISSUE TITLE
SpanRef should have access to attributes values

### ISSUE THREAD

**Issue by maximebedard** [tokio-rs/tracing#682]
### Version

```
├── tracing v0.1.13
│   ├── tracing-attributes v0.1.7
│   └── tracing-core v0.1.10
├── tracing-core v0.1.10 (*)
├── tracing-futures v0.2.3
│   └── tracing v0.1.13 (*)
├── tracing-serde v0.1.1
│   └── tracing-core v0.1.10 (*)
└── tracing-subscriber v0.2.4
    ├── tracing-core v0.1.10 (*)
    ├── tracing-log v0.1.1
    │   └── tracing-core v0.1.10 (*)
    └── tracing-serde v0.1.1 (*)
```

### Platform

Linux ubuntu-bionic 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Crates

tracing_subscriber

### Description

Hello! I'm trying to build a formatter that would also include the attributes from previous spans for the events produced. It seems to be similar to [inherit_fields](https://docs.rs/tracing-subscriber/0.2.4/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.inherit_fields) that was available in the previous versions. 

I've tried a code similar to this one (it doesn't actually compile):

```rust
let formatter = |ctx: &FmtContext<S, N>, writer: &mut dyn Write, evt: &Event| {
  visit = || {
    let mut serializer = JsonSerializer::new(WriteAdaptor::new(writer));

    let mut tags = serializer.serialize_map(None)?;
    let mut visitor = tracing_serde::SerdeMapVisitor::new(tags);

    ctx.visit_spans(|spanref| -> Result<(), io::Error> {
      spanref.record(&mut visitor)?; // Not possible since the SpanRef only has a reference to the metadata, not the actual Span/Event.
      Ok(())
    });

    visitor.finish()?;
  }
  visit().map_err(|_| fmt::Error)?;
  writeln!(writer)
}

fmt::Subscriber::builder().event_format(formatter).init()

{
  let span = info_span!("foo", answer = 42);
  let _span = span.enter()
  info!("bar")
}

// expected result {"answer": "42"}
```

How would one achieve a similar result using the newer version of the crate? Should I be persisting contextual data in layers instead? Should the data stored in the registry have a reference to FieldValues?

**Comment by davidbarsky** [comment]
> Should I be persisting contextual data in layers instead? 

Yes, that's the approach we suggest taking. `tracing_subscriber`'s  [`Extensions`](https://docs.rs/tracing-subscriber/0.2.4/tracing_subscriber/registry/index.html) can be considered to be a generalization of the `inherit_fields` method, but for storing _completely_ arbitrary data, not _just_  data that `tracing_subscriber` decides to format as a string. As a simple example, take a look at my [`tracing-tree` library which records all fields and values](https://github.com/davidbarsky/tracing-tree/blob/master/src/lib.rs#L135-L139) via `Layer::new_span` method. A more complex/involved example would be [`tracing-error`](https://github.com/tokio-rs/tracing/tree/master/tracing-error), which allows span data to be recorded at the span's callsite.

**Comment by hawkw** [comment]
Field values are (potentially) borrowed from the scope where they are recorded, so they can't be stored for the span's entire lifecycle. Instead, the layer can store its own representation of whatever field data it cares about in the span's `Extensions`, as David noted. 

Since you're writing a custom formatter for `tracing_subscriber::fmt`, you can use the `FormattedFields` extension. The `fmt` layer stores a `FormattedFields` extension containing a formatted representation of each span's fields when that span is created:
https://github.com/tokio-rs/tracing/blob/aeca93883ffcc482e9b8f26251877092f3c66290/tracing-subscriber/src/fmt/fmt_layer.rs#L430-L439
Your event formatter can then look up the `FormattedFields` extension when formatting an event. Here's what the default formatter does: 
https://github.com/tokio-rs/tracing/blob/aeca93883ffcc482e9b8f26251877092f3c66290/tracing-subscriber/src/fmt/format/mod.rs#L664-L676

We may want to consider adding a convenience method to the `FmtContext` type to look up the formatted fields of a span, to make this a little more ergonomic for people writing event formatters.

As a side note, if you're writing a formatter that brings back the `inherit_fields` formatting from `tracing-fmt`, I would be _very_ happy to see a PR to add that to `tracing-subscriber`'s format module. :)

**Comment by maximebedard** [comment]
Amazing, thanks for the extremely quick feedback!

> Field values are (potentially) borrowed from the scope where they are recorded, so they can't be stored for the span's entire lifecycle.

That's what I thought and got quickly stuck. I didn't really understand how the concept of layers worked, but with the examples you've provided it should be good enough to get me started! 

I'll take a stab at it and try to open an upstream PR once I have something that works.

**Comment by maximebedard** [comment]
Thanks to your feedback, I was able to get something working! I'll try to work on an implementation upstream on my free time. 😄 For posterity, here's a snippet of what I ended up using:

```rust
ctx.visit_spans(|span| -> Result<(), serde_json::error::Error> {
  let ext = span.extensions();
  let data = ext
    .get::<FormattedFields<N>>()
    .expect("Unable to find FormattedFields in extensions. Your subscriber must use the fmt_layer.");

  let fields: serde_json::Value = serde_json::from_str(data)?;
  if let serde_json::Value::Object(map) = fields {
    for (k, v) in map {
      context.insert(k, v);
    }
  }
  Ok(())
})?;
```

**Comment by hawkw** [comment]
@maximebedard I think that there are no remaining open questions for this ticket, and we can close it now, right?
