### ISSUE TITLE
#[instrument] does not warn on unrecognized options

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tracing#727]
### Version

```
tracing 0.1.14
```

### Description

The following code currently compiles without warnings or errors:

```rust
use tracing::instrument;

#[instrument(debug)]
fn foo() {}
```

A particularly unobservant user (like myself) may try this without reading the documentation carefully, and will likely be very confused why `foo` shows up even at `info` level. It'd be good to warn when unsupported attribute options are used, and ideally also suggest what to use instead (`level = "debug"`) for things like `debug`/`trace`/etc. We _probably_ don't want it to be a hard error for forward-compatibility.

Separately, wouldn't it be kind of nice to support this short-hand syntax? :p

**Comment by hawkw** [comment]
#672 will make `instrument` error on unrecognized syntax. I'm not sure if we can easily emit warnings rather than errrors from proc macros, but I can take a look at it.

> Separately, wouldn't it be kind of nice to support this short-hand syntax? :p

Sure, we could probably add something like that!

**Comment by hawkw** [comment]
Well, it turns out that there isn't currently a good way to emit custom warnings from proc macros on stable (there _is_ a nightly-only API, though!).

However, I figured out a bit of a hack to turn the failure on unrecognized input from #627 into a warning:
![Screenshot_20200707_112812](https://user-images.githubusercontent.com/2796466/86826178-37d1e380-c045-11ea-8aca-be500608779f.png)
it's not the greatest, since it's not _actually_ a deprecation, but at least it emits an actual warning, and works on stable. Unlike #672, this is not a breaking change.
