### ISSUE TITLE
tracing-appender activates default features of tracing-subscriber

### ISSUE THREAD

**Issue by str4d** [tokio-rs/tracing#777]
`tracing-appender` has `tracing-subscriber` as a dependency, and AFAICT it only relies on the `fmt` feature. However, it does not specify `default-features = false, features = ["fmt"]`. This forces all default features to be enabled when `tracing-appender` is in the dependency tree, even when the application also only wants to use the `fmt` feature.

**Comment by hawkw** [comment]
Thanks for the report. We should definitely add `default-features = false` to the dependency. I believe you're right and `fmt` is the only feature that `tracing-appender` requires.

If you're interested in submitting a quick PR to fix this, I'd happily merge it and publish a new release. Otherwise, I'll fix it as soon as I have the time to sit down and make the change.
