### ISSUE TITLE
instrument macro doesn't allow declaration of fields that have a period . in their name

### ISSUE THREAD

**Issue by glademiller** [tokio-rs/tracing#785]
### Motivation

I would like to set http.status_code to empty in order to be able to record the value later the most convenient way to do this would be with the macro.

### Proposal

Allow
#[tracing::instrument(fields(http.status_code = ...))]

### Alternatives

Allow recording of fields without declaring them upfront.

**Comment by hawkw** [comment]
This was implemented in #672. However, it has yet to be released as that PR also causes `instrument` to reject unrecognized input that it did not previously reject, which we think may constitute a breaking change (https://github.com/tokio-rs/tracing/pull/773#issuecomment-652052525). Stay tuned, though --- I'm planning on trying to make some additional changes to make that change backwards compatible.

**Comment by glademiller** [comment]
@hawkw awesome thanks for the update. Would this also allow for declaring the value on that field in the macro to be tracing::field::Empty? I suppose I can always just put another dummy value but being able to use Empty would more clearly communicate my intent.

**Comment by hawkw** [comment]
Yup, that's right. :) 

Currently, field names with no value in `instrument` are mapped to `tracing::field::Empty`, which is what that PR does as well, for backwards-compatibility (although you will also be able to use `Empty` explicitly as well when #672 is published) . However, in `tracing-attributes` 0.2, we want to change this so that `instrument` supports the same local variable shorthand as the function-like `tracing` macros, so you will _need_ to use `Empty` explicitly instead, the same as all the other macros.
