### ISSUE TITLE
Why is the Value trait unimplementable?

### ISSUE THREAD

**Issue by kitsuneninetails** [tokio-rs/tracing#821]
I'm trying to be able to send my own type as a Value, which means I am trying to implement Value for my own type.  Using the "%value" yields the wrong data, even when I implement Display.  So, I want to make this simple and just make my own struct a "Value", but I am artificially restrained from doing so, because the Value trait is "sealed" behind that ridiculous "sealed" crate pattern.

I am so tired of this, and it makes no sense to me.  This is the nth time I have tried to implement a cool feature (seriously, it happens so often, I am almost bald from all the hair-pulling frustration) only to be stopped by another dogmatic dev's crusade to artificially block and limit others from using their code.

Why??  Why won't you allow developers to flex their own muscle and harness the power of Rust's trait system?  Why are you artificially creating barriers to productivity?  Is it because you think other devs are not smart enough to know how to implement traits?  Is it because you think we are so foolish as to not know an internal trait may have odd behavior if we implement it?  Do you think you are so illiterate that we can't read documentation about what caveats implementing a trait might contain?

Seriously.  Trust us.  Free us.  Free yourselves, and stop hiding potentially useful features behind "sealed" crates!

**Comment by hawkw** [comment]
Unsealing the `Value` trait is a long-term goal for the project. When `tracing` was initially released, we determined that it was an important requirement to be able to support interoperability with the `log` crate's structured key-value API, and with other serialization systems (such as `serde`). However, at the time, the `log` key-value API's design was in a much earlier stage of development, and the proposal was changing very frequently. Therefore, we decided to ship an _incomplete_ implementation of our `Value` system for forward-compatibility with whatever design `log` ended up settling on. We thought that this was worth it in order to avoid inflicting the pain of potential breaking changes on our users, even though it _is_ artificially limiting.

Now, however, `log` has published their structured key-value implementation, so there has been some discussion about unsealing `Value`, now that we can ensure compatibility, so that users can provide implementation of `Value` for arbitrary types. There are some unanswered design questions about how best to do this, especially since we also want to support interoperability with serialization systems like `serde`. 

Hopefully that answers your questions about the motivation behind the current state of things. If you'd like to get involved, this issue is tracking work on extending `Value` to support more complex serialization: https://github.com/tokio-rs/tracing/issues/819. Note that some conversation around this has also been taking place [on Discord](https://discord.gg/tokio).

I'm going to close this issue, since further discussion of this should take place on #819.
