### ISSUE TITLE
tracing-subscriber: 0.2.8 requires MSRV 1.43.0

### ISSUE THREAD

**Issue by str4d** [tokio-rs/tracing#840]
The current MSRV of `tracing-subscriber` is 1.39:
https://github.com/tokio-rs/tracing/blob/ca960ff7cb074bdd5357466624acca765220ce2d/tracing-subscriber/src/fmt/mod.rs#L19

However, #807 (released in  `tracing-subscriber 0.2.8`) introduced a dependency on `i64::MAX`, [introduced in 1.43.0](https://doc.rust-lang.org/stable/std/primitive.i64.html#associatedconstant.MAX):
https://github.com/tokio-rs/tracing/blob/ca960ff7cb074bdd5357466624acca765220ce2d/tracing-subscriber/src/fmt/time/datetime.rs#L55

The alternative to bumping MSRV is to switch to `std::i64::MAX` in a point revision.

**Comment by hawkw** [comment]
Whoops, thanks for catching that. Let's just switch to `std::i64::MAX`.

**Comment by hawkw** [comment]
It looks like the CI job that checks for MSRV compliance missed this, because it only checks default features, and this code doesn't exist when a default feature is enabled. 

We should probably also change the MSRV check job to run with more feature combinations (but that will probably make CI much slower...).
