### ISSUE TITLE
Distributed tracing

### ISSUE THREAD

**Issue by kazimuth** [tokio-rs/tracing#89]
I saw a little bit of discussion of this in tokio-rs/tokio#561, but there aren't currently any open issues for it, so I figured I'd start one.

Distributed tracing is like tokio-trace but extended for distributed systems; instead of tracing only within a single process, you can trace code execution of code across process boundaries, machines, data centers, continents... There are a number of systems for this, e.g. [Jaeger](https://www.jaegertracing.io/), [zipkin](https://zipkin.apache.org/), a [bunch of others](https://opentracing.io/docs/supported-tracers/). Tokio-trace is perfectly set up to support distributed tracing, only the actual glue code needs to be written.

1. Trace propagation -- in a distributed tracing system, incoming and outgoing requests to a process are annotated with some form of ID, so that they can be collated later. In the past, tracing systems defined their own bespoke propagation formats, but going forward it looks like people are standardizing on the [W3C Trace Context Recommendation](https://github.com/w3c/trace-context).

2. Trace export -- after traces are recorded, they need to be sent to a central location for viewing. This can be done push-style (having your application connect somewhere and send data) or pull-style (exposing data on some port that can later be scraped). There are open APIs for doing this -- OpenTracing and OpenCensus, which are currently merging into [OpenTelemetry](https://opentelemetry.io/).

I think the simplest path forward on this is to build:
- A parser for W3C TraceContext
- Integrations of that parser with various ecosystem libraries (http, hyper, grpc, actix, rocket, reqwests, ...).
- An exporter for the [OpenCensus service](https://opencensus.io/service/). That service acts as basically a multiplexer - you run a little daemon on your server and send traces to it, then it can send them to jaeger, zipkin, etc for you. OpenTelemetry will be backwards-compatible with this.

Ideally end users should be able to do:
```rust
fn main() {
    opencensus::export();
    actix_web::App::new()
       .middleware(TraceContextMiddleware::new())
       /* ... */
       .finish();
}
```

and have things just work ✨

**Comment by anton-dutov** [comment]
Have you looked at the rustracing / rustracing_jaeger crates for impl ideas?

**Comment by pkinsky** [comment]
I've been playing around with a tracing honeycomb subscriber and one of the things I've had to spend some time thinking about is how trace ids are generated/discovered.

My initial impl just generates a trace id for all top-level spans, but it might make more sense to make this explicit instead of implicit. For example, in a GRPC service I'm building, I think I want to either generate per-request tracing ids or pick up external tracing ids at the request handler level.

**Comment by thedodd** [comment]
OT/Jaeger support would definitely be a pretty big win!

**Comment by bbigras** [comment]
Any progress on this?

**Comment by hawkw** [comment]
@bbigras depending on what distributed tracing system you're using, there are some (work in progress) implementations available: [`tracing-opentelemetry`](https://crates.io/crates/tracing-opentelemetry) for OpenTelemetry, and the [`honeycomb-tracing`](https://crates.io/crates/honeycomb-tracing) crate @pkinsky mentions in https://github.com/tokio-rs/tracing/issues/89#issuecomment-544639597 for Honeycomb users.

**Comment by pkinsky** [comment]
@bbigras I've updated the honeycomb-tracing crate to support arbitrary backends (not just honeycomb) in a branch. Currently all tests are passing, I'll be publishing this new version sometime in the next week.

**Comment by thedodd** [comment]
@pkinsky nice! Does it support OpenTelemetry / Jaeger and such? I'm not a big fan of all the ceremony required in getting the `tracing-opentelemetry` crate setup, especially because it is using the `rustracing_jaeger` crate under the hood, and setting that up is even more painful. The setup for you honeycomb crate looks pretty terse. I like.

**Comment by inanna-malick** [comment]
In theory it should support pretty much any tracing backend, all you need to do is implement this trait with whatever backing logic you prefer:

```rust
pub trait Telemetry {
    type Visitor: Default + tracing::field::Visit;

    fn report_span<'a>(&self, span: Span<'a, Self::Visitor>);
    fn report_event<'a>(&self, event: Event<'a, Self::Visitor>);
}
```

**Comment by davidbarsky** [comment]
@velvia: I've opened a discussion https://github.com/tokio-rs/tracing/discussions/1991 to address your question.

---

Since this functionality already exists through libraries such as [tracing-opentelemetry](https://docs.rs/tracing-opentelemetry/latest/tracing_opentelemetry/) and [tracing-honeycomb](https://github.com/inanna-malick/tracing-honeycomb), I'll close this issue.
